"""Дефолтні CMS-блоки демо-магазину (registry-driven, редагування у «Мій магазин»)."""
from django.utils.translation import gettext_lazy as _

TEXT = 'text'
IMAGE = 'image'

PAGE_LABELS = {
    'header': _('Хедер і стрічка'),
    'home': _('Головна сторінка'),
    'catalog': _('Каталог'),
    'footer': _('Футер'),
}

BLOCK_REGISTRY = [
    {'page': 'header', 'key': 'shop_name', 'type': TEXT, 'label': _('Назва магазину (лого)'),
     'default': 'Demo Shop', 'default_en': 'Demo Shop', 'default_cs': 'Demo Shop', 'default_ru': 'Demo Shop'},
    {'page': 'header', 'key': 'announcement_text', 'type': TEXT, 'label': _('Текст бігучої стрічки'),
     'default': 'Безкоштовна доставка від 1000 грн · Оплата при отриманні · Повернення 14 днів',
     'default_en': 'Free shipping from 1 500 Kč · Cash on delivery · 14-day returns',
     'default_cs': 'Doprava zdarma od 1 500 Kč · Platba při doručení · Vrácení do 14 dnů',
     'default_ru': 'Бесплатная доставка от 1000 грн · Оплата при получении · Возврат 14 дней'},

    {'page': 'home', 'key': 'hero_title', 'type': TEXT, 'label': _('Заголовок hero'),
     'default': 'Все для затишного дому', 'default_en': 'Everything for a cozy home',
     'default_cs': 'Vše pro pohodlný domov', 'default_ru': 'Всё для уютного дома'},
    {'page': 'home', 'key': 'hero_subtitle', 'type': TEXT, 'label': _('Підзаголовок hero'), 'multiline': True,
     'default': 'Каталог перевірених товарів з швидкою доставкою по всій Україні',
     'default_en': 'Catalog of verified products with fast delivery across Czechia',
     'default_cs': 'Katalog ověřených produktů s rychlým doručením po celé ČR',
     'default_ru': 'Каталог проверенных товаров с быстрой доставкой по всей Украине'},
    {'page': 'home', 'key': 'hero_cta_label', 'type': TEXT, 'label': _('Текст кнопки hero'),
     'default': 'Перейти в каталог', 'default_en': 'View catalog', 'default_cs': 'Přejít do katalogu',
     'default_ru': 'Перейти в каталог'},
    {'page': 'home', 'key': 'about_title', 'type': TEXT, 'label': _('Заголовок «Про нас»'),
     'default': 'Чому обирають нас', 'default_en': 'Why choose us', 'default_cs': 'Proč si vybrat nás',
     'default_ru': 'Почему выбирают нас'},
    {'page': 'home', 'key': 'about_text', 'type': TEXT, 'label': _('Текст «Про нас»'), 'multiline': True,
     'default': 'Ми працюємо з 2019 року і відправляємо замовлення по всій країні протягом 24 годин.',
     'default_en': 'We have been working since 2019 and ship orders nationwide within 24 hours.',
     'default_cs': 'Působíme od roku 2019 a objednávky odesíláme po celé zemi do 24 hodin.',
     'default_ru': 'Мы работаем с 2019 года и отправляем заказы по всей стране в течение 24 часов.'},
    {'page': 'home', 'key': 'about_image', 'type': IMAGE, 'label': _('Фото «Про нас»')},
    {'page': 'home', 'key': 'stat_orders', 'type': TEXT, 'label': _('Статистика: замовлень'),
     'default': '12 400+', 'default_en': '12,400+', 'default_cs': '12 400+', 'default_ru': '12 400+'},
    {'page': 'home', 'key': 'stat_clients', 'type': TEXT, 'label': _('Статистика: клієнтів'),
     'default': '8 900+', 'default_en': '8,900+', 'default_cs': '8 900+', 'default_ru': '8 900+'},
    {'page': 'home', 'key': 'stat_rating', 'type': TEXT, 'label': _('Статистика: рейтинг'),
     'default': '4.9 / 5', 'default_en': '4.9 / 5', 'default_cs': '4.9 / 5', 'default_ru': '4.9 / 5'},

    {'page': 'catalog', 'key': 'catalog_title', 'type': TEXT, 'label': _('Заголовок каталогу'),
     'default': 'Каталог товарів', 'default_en': 'Product Catalog', 'default_cs': 'Katalog produktů',
     'default_ru': 'Каталог товаров'},
    {'page': 'catalog', 'key': 'catalog_subtitle', 'type': TEXT, 'label': _('Підзаголовок каталогу'),
     'default': 'Оберіть категорію або скористайтесь пошуком', 'default_en': 'Choose a category or use the search',
     'default_cs': 'Vyberte kategorii nebo použijte vyhledávání',
     'default_ru': 'Выберите категорию или воспользуйтесь поиском'},

    {'page': 'footer', 'key': 'footer_text', 'type': TEXT, 'label': _('Текст футера'), 'multiline': True,
     'default': 'Демо-магазин згенеровано PrometeyLabs як приклад CMS-функціоналу.',
     'default_en': 'Demo store generated by PrometeyLabs as an example of CMS functionality.',
     'default_cs': 'Demo obchod vygenerován společností PrometeyLabs jako ukázka CMS funkcí.',
     'default_ru': 'Демо-магазин сгенерирован PrometeyLabs как пример CMS-функционала.'},
    {'page': 'footer', 'key': 'footer_phone', 'type': TEXT, 'label': _('Телефон у футері'),
     'default': '+38 (063) 000-00-00', 'default_en': '+420 777 000 000', 'default_cs': '+420 777 000 000',
     'default_ru': '+38 (063) 000-00-00'},
    {'page': 'footer', 'key': 'footer_email', 'type': TEXT, 'label': _('Email у футері'),
     'default': 'shop@example.com', 'default_en': 'shop@example.com', 'default_cs': 'shop@example.com',
     'default_ru': 'shop@example.com'},
]


def get_block_entry(page: str, key: str):
    for entry in BLOCK_REGISTRY:
        if entry['page'] == page and entry['key'] == key:
            return entry
    return None
