# Generated by Django 5.2 on 2025-09-02 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('color', models.CharField(default='#DC143C', max_length=7, verbose_name='Колір категорії')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Іконка')),
            ],
            options={
                'verbose_name': 'Категорія подій',
                'verbose_name_plural': 'Категорії подій',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва події')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('excerpt', models.TextField(max_length=300, verbose_name='Короткий опис')),
                ('content', models.TextField(verbose_name='Повний опис')),
                ('event_type', models.CharField(choices=[('webinar', 'Вебінар'), ('discount', 'Знижка'), ('course', 'Курс'), ('workshop', 'Майстер-клас'), ('meetup', 'Зустріч'), ('other', 'Інше')], max_length=20, verbose_name='Тип події')),
                ('status', models.CharField(choices=[('upcoming', 'Майбутня'), ('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Скасована')], default='upcoming', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateTimeField(verbose_name='Дата та час початку')),
                ('end_date', models.DateTimeField(verbose_name='Дата та час завершення')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн реєстрації')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Місце проведення')),
                ('is_online', models.BooleanField(default=True, verbose_name='Онлайн подія')),
                ('meeting_link', models.URLField(blank=True, verbose_name='Посилання на зустріч')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна')),
                ('discount_percent', models.IntegerField(default=0, verbose_name='Відсоток знижки')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оригінальна ціна')),
                ('max_participants', models.IntegerField(blank=True, null=True, verbose_name='Максимальна кількість учасників')),
                ('current_participants', models.IntegerField(default=0, verbose_name='Поточна кількість учасників')),
                ('image', models.ImageField(blank=True, upload_to='events/', verbose_name='Зображення події')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO заголовок')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO опис')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='Ключові слова')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендована')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventcategory', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Подія',
                'verbose_name_plural': 'Події',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Компанія')),
                ('message', models.TextField(blank=True, verbose_name='Додаткова інформація')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата реєстрації')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Підтверджено')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Подія')),
            ],
            options={
                'verbose_name': 'Реєстрація на подію',
                'verbose_name_plural': 'Реєстрації на події',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'email')},
            },
        ),
    ]
