# Generated by Django 5.2.4 on 2025-10-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='color',
            field=models.CharField(default='#E65100', max_length=7, verbose_name='Колір категорії'),
        ),
    ]
