services:
  - type: web
    plan: starter
    name: prometei-web
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "./scripts/start.sh"
    disk:
      name: prometey-media
      mountPath: /opt/render/project/src/media
      sizeGB: 1
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: RENDER_EXTERNAL_HOSTNAME
        value: prometeylabs.com
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: LANGUAGE_CODE
        value: uk
      - key: SITE_URL
        value: "https://www.prometeylabs.com"
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: DEFAULT_FROM_EMAIL
        value: "Prometey Labs <info@prometeylabs.com>"
      - key: CONTACT_EMAIL
        value: "info@prometeylabs.com"
      - key: KEYCRM_API_KEY
        sync: false
      - key: KEYCRM_PIPELINE_ID
        value: "1"
      - key: KEYCRM_SOURCE_ID
        sync: false
      - key: KEYCRM_GCLID_FIELD_UUID
        sync: false
      - key: KEYCRM_WEBHOOK_SECRET
        generateValue: true
      - key: KEYCRM_SUCCESS_STATUS_ID
        sync: false
      - key: KEYCRM_SOURCE_PAID_SHOPS
        sync: false
      - key: KEYCRM_SOURCE_PAID_CORPORATE
        sync: false
      - key: KEYCRM_SOURCE_PAID_ALL
        sync: false
      - key: KEYCRM_SOURCE_ORGANIC_SHOPS
        sync: false
      - key: KEYCRM_SOURCE_ORGANIC_CORPORATE
        sync: false
      - key: KEYCRM_UTM_MATCH_PAID_CORPORATE
        sync: false
      - key: KEYCRM_UTM_MATCH_PAID_SHOPS
        sync: false
      - key: KEYCRM_UTM_MATCH_PAID_ALL
        sync: false
      - key: GOOGLE_ADS_DEVELOPER_TOKEN
        sync: false
      - key: GOOGLE_ADS_CLIENT_ID
        sync: false
      - key: GOOGLE_ADS_CLIENT_SECRET
        sync: false
      - key: GOOGLE_ADS_REFRESH_TOKEN
        sync: false
      - key: GOOGLE_ADS_CUSTOMER_ID
        sync: false
      - key: GOOGLE_ADS_CONVERSION_ACTION_ID
        sync: false