# Generated by Django 4.2.21 on 2026-09-06 12:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_proposal_kind_and_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, max_length=160, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Вимкнено — вітрина й адмінка клієнта повертають 404', verbose_name='Активний')),
                ('demo_login', models.CharField(blank=True, max_length=150, verbose_name='Логін (демо)')),
                ('demo_password', models.CharField(blank=True, help_text='Показується лише в цій адмінці — для передачі клієнту', max_length=150, verbose_name='Пароль (демо)')),
                ('color_primary', models.CharField(blank=True, help_text='Hex, напр. #D6CEC7. Порожньо = дефолт', max_length=7, validators=[django.core.validators.RegexValidator(message='Формат кольору: #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Основний колір')),
                ('color_primary_hover', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Формат кольору: #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Основний колір (hover)')),
                ('color_accent', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Формат кольору: #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Акцентний колір')),
                ('color_surface', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Формат кольору: #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Фон секцій')),
                ('color_text', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Формат кольору: #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір тексту')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('style_preset', models.CharField(choices=[('dark_premium', 'Dark Premium'), ('mixed', 'Mixed (темний hero + світлі секції)'), ('light_minimal', 'Light Minimal')], default='mixed', max_length=20, verbose_name='Стиль')),
                ('hero_mode', models.CharField(choices=[('cinematic', 'Кінематографічне фото'), ('scroll_video', 'Scroll-scrubbed відео')], default='cinematic', max_length=20, verbose_name='Режим hero')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='demolanding/hero/', verbose_name='Hero — фото (широке)')),
                ('hero_image_narrow', models.ImageField(blank=True, null=True, upload_to='demolanding/hero/', verbose_name='Hero — фото (мобільне)')),
                ('hero_video', models.FileField(blank=True, null=True, upload_to='demolanding/hero/', verbose_name='Hero — відео (scroll-video)')),
                ('hero_poster', models.ImageField(blank=True, null=True, upload_to='demolanding/hero/', verbose_name='Hero — poster для відео')),
                ('owner_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_landing', to=settings.AUTH_USER_MODEL, verbose_name='Клієнтський логін')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_landing', to='core.proposal', verbose_name='Комерційна пропозиція')),
            ],
            options={
                'verbose_name': 'Демо-лендінг',
                'verbose_name_plural': 'Демо-лендінги',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LandingTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150, verbose_name='Автор')),
                ('role', models.CharField(blank=True, max_length=150, verbose_name='Роль / проєкт')),
                ('text', models.TextField(verbose_name='Текст')),
                ('text_ru', models.TextField(blank=True, verbose_name='Текст (RU)')),
                ('text_en', models.TextField(blank=True, verbose_name='Текст (EN)')),
                ('text_cs', models.TextField(blank=True, verbose_name='Текст (CS)')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оцінка')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='demolanding/testimonials/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='demolanding.landingsite', verbose_name='Лендінг')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LandingPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('logo', models.ImageField(upload_to='demolanding/partners/', verbose_name='Лого')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='demolanding.landingsite', verbose_name='Лендінг')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнери',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LandingOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва послуги')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Назва (RU)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Назва (EN)')),
                ('title_cs', models.CharField(blank=True, max_length=200, verbose_name='Назва (CS)')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('description_ru', models.TextField(blank=True, verbose_name='Опис (RU)')),
                ('description_en', models.TextField(blank=True, verbose_name='Опис (EN)')),
                ('description_cs', models.TextField(blank=True, verbose_name='Опис (CS)')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна від')),
                ('image', models.ImageField(blank=True, null=True, upload_to='demolanding/offers/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='demolanding.landingsite', verbose_name='Лендінг')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LandingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Імʼя')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='demolanding.landingsite', verbose_name='Лендінг')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LandingGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='demolanding/gallery/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Підпис')),
                ('caption_ru', models.CharField(blank=True, max_length=200, verbose_name='Підпис (RU)')),
                ('caption_en', models.CharField(blank=True, max_length=200, verbose_name='Підпис (EN)')),
                ('caption_cs', models.CharField(blank=True, max_length=200, verbose_name='Підпис (CS)')),
                ('span', models.CharField(choices=[('1x1', '1×1'), ('2x1', '2×1'), ('1x2', '1×2')], default='1x1', max_length=6, verbose_name='Розмір у сітці')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='demolanding.landingsite', verbose_name='Лендінг')),
            ],
            options={
                'verbose_name': 'Фото галереї',
                'verbose_name_plural': 'Галерея',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LandingBeforeAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Підпис')),
                ('image_before', models.ImageField(upload_to='demolanding/before_after/', verbose_name='До')),
                ('image_after', models.ImageField(upload_to='demolanding/before_after/', verbose_name='Після')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='before_after_pairs', to='demolanding.landingsite', verbose_name='Лендінг')),
            ],
            options={
                'verbose_name': 'До / після',
                'verbose_name_plural': 'До / після',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LandingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(db_index=True, max_length=40, verbose_name='Сторінка')),
                ('key', models.CharField(max_length=60, verbose_name='Ключ')),
                ('block_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Зображення'), ('bool', 'Перемикач (видимість секції)')], default='text', max_length=10, verbose_name='Тип')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='Підпис для адмінки')),
                ('value_text', models.TextField(blank=True, verbose_name='Текст')),
                ('value_text_ru', models.TextField(blank=True, verbose_name='Текст (RU)')),
                ('value_text_en', models.TextField(blank=True, verbose_name='Текст (EN)')),
                ('value_text_cs', models.TextField(blank=True, verbose_name='Текст (CS)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('value_image', models.ImageField(blank=True, null=True, upload_to='demolanding/blocks/', verbose_name='Зображення')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='demolanding.landingsite', verbose_name='Лендінг')),
            ],
            options={
                'verbose_name': 'Блок контенту',
                'verbose_name_plural': 'Блоки контенту',
                'ordering': ('page', 'order', 'id'),
                'unique_together': {('tenant', 'page', 'key')},
            },
        ),
    ]
