# Generated by Django 4.2.21 on 2026-01-30 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('messenger_link', models.URLField(blank=True, verbose_name='Посилання на месенджер')),
                ('form_type', models.CharField(choices=[('site-request', 'Заявка на розробку сайту'), ('developer', 'Заявка на курси'), ('consultation', 'Заявка на консультацію'), ('contact', 'Заявка зі сторінки контактів'), ('call-request', 'Замовлення дзвінка'), ('footer-consultation', 'Заявка з footer'), ('event_registration', 'Реєстрація на подію'), ('test_result', 'Результат тесту калькулятора')], db_index=True, max_length=30, verbose_name='Тип форми')),
                ('status', models.CharField(choices=[('new', 'Новий'), ('in_progress', 'В роботі'), ('thinking', 'Думає / Очікує'), ('no_contact', "Не на зв'язку"), ('ordered', 'Замовив сайт'), ('rejected', 'Відмова / Архів')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низький'), ('normal', 'Нормальний'), ('high', 'Високий')], default='normal', max_length=10, verbose_name='Пріоритет')),
                ('details', models.TextField(blank=True, verbose_name='Деталі / Повідомлення')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='Додаткові дані')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адреса')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Коментар менеджера')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Призначено')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_formsu_created_243255_idx'), models.Index(fields=['status'], name='core_formsu_status_cbd577_idx'), models.Index(fields=['form_type'], name='core_formsu_form_ty_50a7f1_idx'), models.Index(fields=['created_at', 'status'], name='core_formsu_created_f17d72_idx')],
            },
        ),
    ]
