# Generated by Django 4.2.21 on 2026-01-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedFormSubmission',
            fields=[
            ],
            options={
                'verbose_name': 'Архівна заявка',
                'verbose_name_plural': 'Архів заявок',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.formsubmission',),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='project',
            field=models.CharField(blank=True, help_text='Короткий опис проекту для швидкого огляду в списку', max_length=200, verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='form_type',
            field=models.CharField(choices=[('manual', 'Ручна заявка'), ('site-request', 'Заявка на розробку сайту'), ('developer', 'Заявка на курси'), ('consultation', 'Заявка на консультацію'), ('contact', 'Заявка зі сторінки контактів'), ('call-request', 'Замовлення дзвінка'), ('footer-consultation', 'Заявка з footer'), ('event_registration', 'Реєстрація на подію'), ('test_result', 'Результат тесту калькулятора')], db_index=True, default='manual', max_length=30, verbose_name='Тип форми'),
        ),
    ]
