# Generated by Django 4.2.21 on 2026-01-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_archivedformsubmission_formsubmission_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='email_sent',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Email відправлено'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час відправки email'),
        ),
    ]
