# Generated by Django 4.2.21 on 2026-02-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_employee_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.CreateModel(
            name='CompletedFormSubmission',
            fields=[
            ],
            options={
                'verbose_name': 'Завершена заявка',
                'verbose_name_plural': 'Завершено',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.formsubmission',),
        ),
        migrations.CreateModel(
            name='InProgressFormSubmission',
            fields=[
            ],
            options={
                'verbose_name': 'Заявка в роботі',
                'verbose_name_plural': 'В роботі',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.formsubmission',),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='status',
            field=models.CharField(choices=[('new', 'Новий'), ('in_progress', 'В роботі'), ('thinking', 'Думає / Очікує'), ('no_contact', "Не на зв'язку"), ('ordered', 'Замовив сайт'), ('completed', 'Завершено'), ('rejected', 'Відмова / Архів')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
