# Generated by Django 4.2.21 on 2026-02-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_employee_completedformsubmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='status',
            field=models.CharField(choices=[('new', 'Новий'), ('in_progress', 'В роботі'), ('thinking', 'Думає / Очікує'), ('no_contact', "Не на зв'язку"), ('back_to_applications', 'Назад в заявки'), ('completed', 'Завершено'), ('pause', 'Пауза'), ('rejected', 'Архів заявок')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
