# Generated by Django 4.2.21 on 2026-02-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_migrate_ordered_to_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='gclid',
            field=models.CharField(blank=True, max_length=255, verbose_name='Google Click ID'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='keycrm_card_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='KeyCRM Card ID'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='keycrm_synced',
            field=models.BooleanField(default=False, verbose_name='Синхронізовано з KeyCRM'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=255, verbose_name='UTM Campaign'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='utm_content',
            field=models.CharField(blank=True, max_length=255, verbose_name='UTM Content'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=255, verbose_name='UTM Medium'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='utm_source',
            field=models.CharField(blank=True, max_length=255, verbose_name='UTM Source'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='utm_term',
            field=models.CharField(blank=True, max_length=255, verbose_name='UTM Term'),
        ),
    ]
