# Generated by Django 4.2.21 on 2026-06-02 13:04

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitecontactsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Підзаголовок')),
                ('card_description', models.TextField(verbose_name='Короткий опис (картка)')),
                ('integrations', models.TextField(blank=True, help_text='Один тег на рядок (без #)', verbose_name='Теги інтеграцій')),
                ('card_image', models.ImageField(upload_to=apps.core.models.portfolio_upload_to, verbose_name='Зображення картки (desktop)')),
                ('card_image_mobile', models.ImageField(blank=True, upload_to=apps.core.models.portfolio_upload_to, verbose_name='Зображення картки (mobile)')),
                ('card_image_alt', models.CharField(blank=True, max_length=255, verbose_name='Alt текст картки')),
                ('home_story_image', models.ImageField(blank=True, upload_to=apps.core.models.portfolio_upload_to, verbose_name='Зображення для головної (stories)')),
                ('home_story_label', models.CharField(blank=True, help_text='Якщо порожньо — використовується заголовок', max_length=100, verbose_name='Назва на головній')),
                ('modal_content', models.TextField(blank=True, verbose_name='Контент модального вікна (HTML)')),
                ('modal_hero', models.ImageField(blank=True, upload_to=apps.core.models.portfolio_upload_to, verbose_name='Модалка: головне зображення')),
                ('modal_mobile', models.ImageField(blank=True, upload_to=apps.core.models.portfolio_upload_to, verbose_name='Модалка: мобільна версія')),
                ('modal_tablet', models.ImageField(blank=True, upload_to=apps.core.models.portfolio_upload_to, verbose_name='Модалка: планшетна версія')),
                ('modal_laptop', models.ImageField(blank=True, upload_to=apps.core.models.portfolio_upload_to, verbose_name='Модалка: десктопна версія')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('show_on_portfolio', models.BooleanField(default=False, verbose_name='Показувати на /portfolio/')),
                ('show_on_homepage', models.BooleanField(default=False, verbose_name='Показувати на головній')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок на /portfolio/')),
                ('home_order', models.PositiveIntegerField(default=0, verbose_name='Порядок на головній')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Проєкт портфоліо',
                'verbose_name_plural': 'Проєкти портфоліо',
                'db_table': 'core_portfolio_project',
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['is_published', 'order'], name='core_portfo_is_publ_748006_idx'), models.Index(fields=['show_on_portfolio', 'is_published'], name='core_portfo_show_on_74a6cf_idx'), models.Index(fields=['show_on_homepage', 'is_published'], name='core_portfo_show_on_0edd7d_idx')],
            },
        ),
    ]
