# Generated by Django 4.2.21 on 2026-06-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_portfolioproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontactsettings',
            name='address',
            field=models.CharField(default='Київ, бульвар Тараса Шевченка 46а', max_length=255, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='tiktok_url',
            field=models.URLField(blank=True, default='https://tiktok.com/@prometeylabs', verbose_name='TikTok'),
        ),
    ]
