# Generated by Django 4.2.21 on 2026-06-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_tiktok_url_and_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='form_type',
            field=models.CharField(choices=[('manual', 'Ручна заявка'), ('site-request', 'Заявка на розробку сайту'), ('developer', 'Заявка на курси'), ('consultation', 'Заявка на консультацію'), ('contact', 'Заявка зі сторінки контактів'), ('call-request', 'Замовлення дзвінка'), ('footer-consultation', 'Заявка з футера'), ('test_result', 'Результат тесту калькулятора')], db_index=True, default='manual', max_length=30, verbose_name='Тип форми'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('logo', models.ImageField(upload_to='clients/', verbose_name='Логотип')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показувати на головній')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
                'db_table': 'core_client',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='core_client_is_acti_83903c_idx')],
            },
        ),
    ]
