# Generated by Django 4.2.21 on 2026-06-09 13:30

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_seed_clients_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioFeatureBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.core.models.feature_block_upload_to, verbose_name='Зображення')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Feature-блок портфоліо Beta',
                'verbose_name_plural': 'Feature-блоки портфоліо Beta',
                'db_table': 'core_portfolio_feature_block',
                'ordering': ['order'],
            },
        ),
    ]
