# Generated by Django 4.2.21 on 2026-06-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_seed_clients_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='card_description_ru',
            field=models.TextField(blank=True, verbose_name='Короткий опис (картка) (RU)'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='card_image_alt_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt текст картки (RU)'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='home_story_label_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Назва на головній (RU)'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='modal_content_ru',
            field=models.TextField(blank=True, verbose_name='Контент модального вікна (HTML) (RU)'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Підзаголовок (RU)'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (RU)'),
        ),
    ]
