# Generated by Django 4.2.21 on 2026-06-22 13:09
#
# PortfolioProject *_ru поля вже додає 0015_add_ru_content_fields (паралельна гілка).
# Тут лише RU-поля для PortfolioFeatureBlock — інакше на Render:
# ProgrammingError: column "card_description_ru" ... already exists

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_portfolio_feature_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliofeatureblock',
            name='text_ru',
            field=models.TextField(blank=True, verbose_name='Текст (RU)'),
        ),
        migrations.AddField(
            model_name='portfoliofeatureblock',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (RU)'),
        ),
    ]
