# Generated by Django 4.2.21 on 2026-09-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_portfolioproject_cta'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontactsettings',
            name='data_protection_email',
            field=models.EmailField(default='info@prometeylabs.com', help_text='Контакт для запитів щодо Privacy Policy (ст. 37 GDPR — окремий DPO не потрібен).', max_length=254, verbose_name='Email відповідальної особи за захист даних'),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='legal_address',
            field=models.CharField(default='Полтавська обл., м. Миргород, вул. Кваші, буд 2', help_text='Місце реєстрації ФОП; фактична адреса — поле «Адреса» вище.', max_length=255, verbose_name='Юридична адреса (Impressum)'),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='legal_name',
            field=models.CharField(default='ФОП Дмитренко Софія Дмитрівна', help_text='Відображається у футері на кожній сторінці сайту.', max_length=255, verbose_name='Юридична назва (Impressum)'),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='registration_number',
            field=models.CharField(default='3770706565', max_length=32, verbose_name='Реєстраційний номер (РНОКПП)'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='form_type',
            field=models.CharField(choices=[('manual', 'Ручна заявка'), ('site-request', 'Заявка на розробку сайту'), ('developer', 'Заявка на курси'), ('consultation', 'Заявка на консультацію'), ('contact', 'Заявка зі сторінки контактів'), ('call-request', 'Замовлення дзвінка'), ('footer-consultation', 'Заявка з футера'), ('test_result', 'Результат тесту калькулятора'), ('tz_generator', 'Генератор ТЗ для сайту')], db_index=True, default='manual', max_length=30, verbose_name='Тип форми'),
        ),
        migrations.AlterField(
            model_name='sitecontactsettings',
            name='facebook_url',
            field=models.URLField(default='https://www.facebook.com/profile.php?id=61577585882254', verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='sitecontactsettings',
            name='linkedin_url',
            field=models.URLField(default='https://www.linkedin.com/in/sofia-dmitrenko', verbose_name='LinkedIn'),
        ),
    ]
