# Generated by Django 4.2.21 on 2026-09-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_sitecontactsettings_data_protection_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='budget',
            field=models.CharField(blank=True, choices=[('to_500', 'до 500 €'), ('500_1500', '500–1500 €'), ('1500_3000', '1500–3000 €'), ('3000_plus', 'від 3000 €'), ('discuss', 'Обговоримо')], db_index=True, default='', max_length=20, verbose_name='Орієнтовний бюджет'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Згода на обробку даних — прийнято'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP при підтвердженні згоди'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='messenger_type',
            field=models.CharField(blank=True, choices=[('phone', 'Телефон'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('viber', 'Viber')], default='', max_length=20, verbose_name="Тип зв'язку / месенджер"),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('cs', 'Čeština'), ('en', 'English'), ('uk', 'Українська')], db_index=True, default='', max_length=5, verbose_name='Бажана мова спілкування'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='project_type',
            field=models.CharField(blank=True, choices=[('site', 'Сайт / лендінг'), ('eshop', 'Інтернет-магазин'), ('webapp', 'Веб-застосунок'), ('other', 'Інше')], db_index=True, default='', max_length=20, verbose_name='Тип проєкту'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
    ]
