# Generated by Django 4.2.21 on 2026-09-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_formsubmission_lead_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='cta_label_cs',
            field=models.CharField(blank=True, max_length=120, verbose_name='Текст CTA (CS)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='cta_label_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Текст CTA (EN)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='guarantee_html_cs',
            field=models.TextField(blank=True, verbose_name='Гарантія (HTML) (CS)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='guarantee_html_en',
            field=models.TextField(blank=True, verbose_name='Гарантія (HTML) (EN)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='intro_html_cs',
            field=models.TextField(blank=True, verbose_name='Про компанію / стек (HTML) (CS)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='intro_html_en',
            field=models.TextField(blank=True, verbose_name='Про компанію / стек (HTML) (EN)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='lead_cs',
            field=models.TextField(blank=True, verbose_name='Лід (CS)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='lead_en',
            field=models.TextField(blank=True, verbose_name='Лід (EN)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='title_cs',
            field=models.CharField(blank=True, max_length=300, verbose_name='Заголовок (CS)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='proposalmodule',
            name='description_cs',
            field=models.TextField(blank=True, verbose_name='Опис (CS)'),
        ),
        migrations.AddField(
            model_name='proposalmodule',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Опис (EN)'),
        ),
        migrations.AddField(
            model_name='proposalmodule',
            name='title_cs',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (CS)'),
        ),
        migrations.AddField(
            model_name='proposalmodule',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='proposalpackage',
            name='duration_cs',
            field=models.CharField(blank=True, max_length=100, verbose_name='Термін (CS)'),
        ),
        migrations.AddField(
            model_name='proposalpackage',
            name='duration_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Термін (EN)'),
        ),
        migrations.AddField(
            model_name='proposalpackage',
            name='name_cs',
            field=models.CharField(blank=True, max_length=200, verbose_name='Назва пакету (CS)'),
        ),
        migrations.AddField(
            model_name='proposalpackage',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Назва пакету (EN)'),
        ),
        migrations.AddField(
            model_name='proposalpackage',
            name='scope_cs',
            field=models.TextField(blank=True, verbose_name='Що входить (CS)'),
        ),
        migrations.AddField(
            model_name='proposalpackage',
            name='scope_en',
            field=models.TextField(blank=True, verbose_name='Що входить (EN)'),
        ),
        migrations.AddField(
            model_name='proposalspec',
            name='body_cs',
            field=models.TextField(blank=True, verbose_name='Текст (CS)'),
        ),
        migrations.AddField(
            model_name='proposalspec',
            name='body_en',
            field=models.TextField(blank=True, verbose_name='Текст (EN)'),
        ),
        migrations.AddField(
            model_name='proposalspec',
            name='title_cs',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (CS)'),
        ),
        migrations.AddField(
            model_name='proposalspec',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (EN)'),
        ),
    ]
