# Generated by Django 4.2.21 on 2026-09-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_proposal_cta_label_cs_proposal_cta_label_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontactsettings',
            name='address_cs',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адреса (CS)'),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адреса (EN)'),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='address_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адреса (RU)'),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='legal_address_cs',
            field=models.CharField(blank=True, max_length=255, verbose_name='Юридична адреса (CS)'),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='legal_address_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Юридична адреса (EN)'),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='legal_address_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Юридична адреса (RU)'),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='legal_name_cs',
            field=models.CharField(blank=True, max_length=255, verbose_name='Юридична назва (CS)'),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='legal_name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Юридична назва (EN)'),
        ),
        migrations.AddField(
            model_name='sitecontactsettings',
            name='legal_name_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Юридична назва (RU)'),
        ),
    ]
