# Generated by Django 4.2.21 on 2026-09-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_sitecontactsettings_address_cs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='corp_catalog',
            field=models.BooleanField(default=False, help_text='Лише для типу «Корпоративний сайт»: додає розділ каталогу без оплат/кошика — кнопка «Купити» відкриває форму заявки.', verbose_name='Каталог на корпоративному сайті'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='kind',
            field=models.CharField(choices=[('shop', 'Інтернет-магазин'), ('landing', 'Лендінг'), ('corporate', 'Корпоративний сайт')], db_index=True, default='shop', help_text='Визначає, яке демо створює дія «Створити/оновити демо»', max_length=20, verbose_name='Тип демо'),
        ),
    ]
