# Generated by Django 4.2.21 on 2026-09-06 12:30

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_proposal_kind_and_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='site_url',
            field=models.URLField(blank=True, help_text='URL реального сайту для management-команди capture_portfolio_screens. Не показується публічно і не веде на нього.', max_length=300, verbose_name='Живий сайт (джерело знімка)'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='card_image',
            field=models.ImageField(blank=True, help_text='Знімок головної сторінки сайту (desktop). Генерується capture_portfolio_screens.', upload_to=apps.core.models.portfolio_upload_to, verbose_name='Зображення картки (desktop)'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='card_image_mobile',
            field=models.ImageField(blank=True, help_text='Знімок головної сторінки сайту (mobile). Генерується capture_portfolio_screens.', upload_to=apps.core.models.portfolio_upload_to, verbose_name='Зображення картки (mobile)'),
        ),
    ]
