# Generated by Django 4.2.21 on 2026-09-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_portfolioproject_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='card_description_cs',
            field=models.TextField(blank=True, verbose_name='Короткий опис (картка) (CS)'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='card_description_en',
            field=models.TextField(blank=True, verbose_name='Короткий опис (картка) (EN)'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='card_image_alt_cs',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt текст картки (CS)'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='card_image_alt_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt текст картки (EN)'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='cta_label_cs',
            field=models.CharField(blank=True, max_length=120, verbose_name='Текст кнопки (CS)'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='cta_label_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Текст кнопки (EN)'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='integrations_cs',
            field=models.TextField(blank=True, verbose_name='Теги інтеграцій (CS)'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='integrations_en',
            field=models.TextField(blank=True, verbose_name='Теги інтеграцій (EN)'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='integrations_ru',
            field=models.TextField(blank=True, verbose_name='Теги інтеграцій (RU)'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='subtitle_cs',
            field=models.CharField(blank=True, max_length=200, verbose_name='Підзаголовок (CS)'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Підзаголовок (EN)'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='title_cs',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (CS)'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (EN)'),
        ),
    ]
