# Generated by Django 5.2 on 2026-09-14 07:29

import apps.core.proposal_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_delete_portfoliofeatureblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Тематичне фото цього КП. Кожне нове КП — своє зображення з адмінки.', upload_to=apps.core.proposal_models.proposal_hero_upload_to, verbose_name='Фото херо'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='recommendations_lead',
            field=models.TextField(blank=True, verbose_name='Лід рекомендацій'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='recommendations_lead_cs',
            field=models.TextField(blank=True, verbose_name='Лід рекомендацій (CS)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='recommendations_lead_en',
            field=models.TextField(blank=True, verbose_name='Лід рекомендацій (EN)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='recommendations_lead_ru',
            field=models.TextField(blank=True, verbose_name='Лід рекомендацій (RU)'),
        ),
        migrations.CreateModel(
            name='ProposalArchNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Перший рядок (найменший порядок) — корінь. Наступні — колонки.', max_length=120, verbose_name='Назва')),
                ('title_ru', models.CharField(blank=True, max_length=120, verbose_name='Назва (RU)')),
                ('title_en', models.CharField(blank=True, max_length=120, verbose_name='Назва (EN)')),
                ('title_cs', models.CharField(blank=True, max_length=120, verbose_name='Назва (CS)')),
                ('caption', models.CharField(blank=True, max_length=120, verbose_name='Підпис')),
                ('caption_ru', models.CharField(blank=True, max_length=120, verbose_name='Підпис (RU)')),
                ('caption_en', models.CharField(blank=True, max_length=120, verbose_name='Підпис (EN)')),
                ('caption_cs', models.CharField(blank=True, max_length=120, verbose_name='Підпис (CS)')),
                ('is_accent', models.BooleanField(default=False, help_text='Помаранчевий акцент колонки (наприклад вітрина).', verbose_name='Акцент')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arch_nodes', to='core.proposal', verbose_name='Пропозиція')),
            ],
            options={
                'verbose_name': 'Вузол архітектури',
                'verbose_name_plural': 'Дерево архітектури',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProposalHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Пункт')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Пункт (RU)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Пункт (EN)')),
                ('title_cs', models.CharField(blank=True, max_length=200, verbose_name='Пункт (CS)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='core.proposal', verbose_name='Пропозиція')),
            ],
            options={
                'verbose_name': 'Херо-пункт',
                'verbose_name_plural': 'Херо-пункти',
                'ordering': ('order', 'id'),
            },
        ),
    ]
