# Generated by Django 5.2 on 2025-09-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('excerpt', models.TextField(max_length=300, verbose_name='Короткий опис')),
                ('content', models.TextField(verbose_name='Контент')),
                ('seo_title', models.CharField(max_length=70, verbose_name='SEO заголовок')),
                ('seo_description', models.CharField(max_length=160, verbose_name='SEO опис')),
                ('keywords', models.CharField(max_length=255, verbose_name='Ключові слова')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Description')),
                ('og_title', models.CharField(blank=True, max_length=60, verbose_name='OG Title')),
                ('og_description', models.CharField(blank=True, max_length=160, verbose_name='OG Description')),
                ('reading_time', models.PositiveIntegerField(default=5, verbose_name='Час читання (хв)')),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/', verbose_name='Головне зображення')),
                ('category', models.CharField(choices=[('web-development', 'Веб-розробка'), ('courses', 'Курси програмування'), ('telegram-bots', 'Telegram боти'), ('business', 'Бізнес'), ('technology', 'Технології')], default='web-development', max_length=50, verbose_name='Категорія')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'Стаття блогу',
                'verbose_name_plural': 'Статті блогу',
                'ordering': ['-created_at'],
            },
        ),
    ]
