# Generated by Django 5.2.4 on 2025-11-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('web-development', 'Веб-розробка'), ('courses', 'Курси програмування'), ('telegram-bots', 'Telegram боти'), ('business', 'Бізнес'), ('technology', 'Технології'), ('ai-development', 'AI розробка'), ('ai-agents', 'AI агенти'), ('ai-automation', 'AI автоматизація')], default='web-development', max_length=50, verbose_name='Категорія'),
        ),
    ]
