# Generated by Django 4.2.21 on 2026-06-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_ru',
            field=models.TextField(blank=True, verbose_name='Контент (RU)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_ru',
            field=models.TextField(blank=True, max_length=300, verbose_name='Короткий опис (RU)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='keywords_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ключові слова (RU)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (RU)'),
        ),
    ]
