# Generated by Django 4.2.21 on 2026-09-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_add_ru_content_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_cs',
            field=models.TextField(blank=True, verbose_name='Контент (CS)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='Контент (EN)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_cs',
            field=models.TextField(blank=True, max_length=300, verbose_name='Короткий опис (CS)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_en',
            field=models.TextField(blank=True, max_length=300, verbose_name='Короткий опис (EN)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='keywords_cs',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ключові слова (CS)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='keywords_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ключові слова (EN)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_cs',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (CS)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (EN)'),
        ),
    ]
