"""Дефолтні CMS-блоки demo-корпоративного сайту PrometeyLabs (registry-driven, «Мій сайт»)."""
from django.utils.translation import gettext_lazy as _

TEXT = 'text'
IMAGE = 'image'
BOOL = 'bool'

PAGE_LABELS = {
    'header': _('Хедер'),
    'home': _('Головна'),
    'production': _('Як працюємо'),
    'about': _('Про нас'),
    'contacts': _('Контакти'),
    'catalog': _('Приклади'),
    'cta': _('Заклик до дії'),
    'footer': _('Футер'),
    'seo': _('SEO'),
}

BLOCK_REGISTRY = [
    {'page': 'header', 'key': 'company_name', 'type': TEXT, 'label': _('Назва компанії (лого)'),
     'default': 'PrometeyLabs', 'default_en': 'PrometeyLabs', 'default_cs': 'PrometeyLabs',
     'default_ru': 'PrometeyLabs'},

    {'page': 'home', 'key': 'hero_title', 'type': TEXT, 'label': _('Заголовок hero'), 'multiline': True,
     'default': 'Кілька сторінок — і люди пишуть вам',
     'default_en': 'A few pages — and people write to you',
     'default_cs': 'Pár stránek — a lidé vám napíšou',
     'default_ru': 'Несколько страниц — и люди пишут вам'},
    {'page': 'home', 'key': 'hero_subtitle', 'type': TEXT, 'label': _('Підзаголовок hero'), 'multiline': True,
     'default': 'Головна, послуги, про нас, контакти. Зрозумілі слова, зручно з телефону. Тексти потім міняєте самі.',
     'default_en': 'Home, services, about, contacts. Clear words, easy on the phone. You change the texts yourself later.',
     'default_cs': 'Domů, služby, o nás, kontakty. Srozumitelná slova, pohodlné v telefonu. Texty pak měníte sami.',
     'default_ru': 'Главная, услуги, о нас, контакты. Понятные слова, удобно с телефона. Тексты потом меняете сами.'},
    {'page': 'home', 'key': 'hero_cta_label', 'type': TEXT, 'label': _('Текст кнопки hero'),
     'default': 'Хочу такий сайт', 'default_en': 'I want a site like this',
     'default_cs': 'Chci takový web', 'default_ru': 'Хочу такой сайт'},
    {'page': 'home', 'key': 'stat_years', 'type': TEXT, 'label': _('Статистика: днів до старту'),
     'default': '14', 'default_en': '14', 'default_cs': '14', 'default_ru': '14'},
    {'page': 'home', 'key': 'stat_windows', 'type': TEXT, 'label': _('Статистика: сторінок'),
     'default': '6', 'default_en': '6', 'default_cs': '6', 'default_ru': '6'},
    {'page': 'home', 'key': 'stat_warranty', 'type': TEXT, 'label': _('Статистика: зручно з телефону'),
     'default': '100', 'default_en': '100', 'default_cs': '100', 'default_ru': '100'},
    {'page': 'home', 'key': 'stat_dealers', 'type': TEXT, 'label': _('Статистика: мов'),
     'default': '4', 'default_en': '4', 'default_cs': '4', 'default_ru': '4'},
    {'page': 'home', 'key': 'stat_windows_label', 'type': TEXT, 'label': _('Підпис KPI: сторінки'),
     'default': 'сторінок у комплекті', 'default_en': 'pages in the set',
     'default_cs': 'stránek v sadě', 'default_ru': 'страниц в комплекте'},
    {'page': 'home', 'key': 'stat_years_label', 'type': TEXT, 'label': _('Підпис KPI: дні'),
     'default': 'днів до старту', 'default_en': 'days to launch',
     'default_cs': 'dní do startu', 'default_ru': 'дней до старта'},
    {'page': 'home', 'key': 'stat_warranty_label', 'type': TEXT, 'label': _('Підпис KPI: телефон'),
     'default': 'зручно з телефону', 'default_en': 'easy on the phone',
     'default_cs': 'pohodlné v telefonu', 'default_ru': 'удобно с телефона'},
    {'page': 'home', 'key': 'stat_dealers_label', 'type': TEXT, 'label': _('Підпис KPI: мови'),
     'default': 'мови одразу', 'default_en': 'languages from day one',
     'default_cs': 'jazyky hned', 'default_ru': 'языка сразу'},
    {'page': 'home', 'key': 'reviews_visible', 'type': BOOL, 'label': _('Показувати відгуки на головній'),
     'default': '1'},
    {'page': 'home', 'key': 'reviews_title', 'type': TEXT, 'label': _('Заголовок відгуків'),
     'default': 'Люди, які вже замовили', 'default_en': 'People who already ordered',
     'default_cs': 'Lidé, kteří už objednali', 'default_ru': 'Люди, которые уже заказали'},
    {'page': 'home', 'key': 'partners_visible', 'type': BOOL, 'label': _('Показувати партнерів на головній'),
     'default': '1'},
    {'page': 'home', 'key': 'catalog_teaser_title', 'type': TEXT, 'label': _('Заголовок блоку каталогу на головній'),
     'default': 'Приклади сайтів, які можна замовити',
     'default_en': 'Example sites you can order',
     'default_cs': 'Příklady webů, které si můžete objednat',
     'default_ru': 'Примеры сайтов, которые можно заказать'},

    {'page': 'production', 'key': 'title', 'type': TEXT, 'label': _('Заголовок сторінки «Як працюємо»'),
     'default': 'Як ми робимо корпоративний сайт',
     'default_en': 'How we make a corporate site',
     'default_cs': 'Jak děláme firemní web',
     'default_ru': 'Как мы делаем корпоративный сайт'},
    {'page': 'production', 'key': 'intro', 'type': TEXT, 'label': _('Вступний текст'), 'multiline': True,
     'default': 'Цей демо-сайт — живий приклад. Так само збираємо головну, послуги, про нас і контакти під вашу компанію.',
     'default_en': 'This demo site is a live example. We assemble home, services, about and contacts for your company the same way.',
     'default_cs': 'Tento demo web je živý příklad. Stejně sestavíme domů, služby, o nás a kontakty pro vaši firmu.',
     'default_ru': 'Этот демо-сайт — живой пример. Так же собираем главную, услуги, о нас и контакты под вашу компанию.'},
    {'page': 'production', 'key': 'step_1', 'type': TEXT, 'label': _('Етап 1'),
     'default': 'Ви розповідаєте, хто ваша компанія',
     'default_en': 'You tell us who your company is',
     'default_cs': 'Řeknete, kdo je vaše firma',
     'default_ru': 'Вы рассказываете, кто ваша компания'},
    {'page': 'production', 'key': 'step_2', 'type': TEXT, 'label': _('Етап 2'),
     'default': 'Показуємо структуру сторінок',
     'default_en': 'We show the page structure',
     'default_cs': 'Ukážeme strukturu stránek',
     'default_ru': 'Показываем структуру страниц'},
    {'page': 'production', 'key': 'step_3', 'type': TEXT, 'label': _('Етап 3'),
     'default': 'Збираємо сайт і підключаємо заявки',
     'default_en': 'We assemble the site and connect requests',
     'default_cs': 'Sestavíme web a napojíme poptávky',
     'default_ru': 'Собираем сайт и подключаем заявки'},
    {'page': 'production', 'key': 'step_4', 'type': TEXT, 'label': _('Етап 4'),
     'default': 'Ви заходите в адмінку й правите самі',
     'default_en': 'You log into the admin and edit yourself',
     'default_cs': 'Vstoupíte do adminu a upravujete sami',
     'default_ru': 'Вы заходите в админку и правите сами'},
    {'page': 'production', 'key': 'certificates_visible', 'type': BOOL, 'label': _('Показувати додаткові екрани'),
     'default': '1'},

    {'page': 'about', 'key': 'title', 'type': TEXT, 'label': _('Заголовок «Про нас»'),
     'default': 'Сайти для компаній', 'default_en': 'Sites for companies',
     'default_cs': 'Weby pro firmy', 'default_ru': 'Сайты для компаний'},
    {'page': 'about', 'key': 'text', 'type': TEXT, 'label': _('Текст «Про нас»'), 'multiline': True,
     'default': 'PrometeyLabs робить корпоративні сайти: не конструктор і не чужий шаблон. Цей демо — приклад того, що ви отримуєте: сторінки, заявки, адмінка, зручно з телефону.',
     'default_en': 'PrometeyLabs builds corporate sites: not a builder and not someone else’s template. This demo is what you get: pages, requests, an admin, easy on the phone.',
     'default_cs': 'PrometeyLabs dělá firemní weby: ne konstruktor a ne cizí šablona. Toto demo je to, co dostanete: stránky, poptávky, admin, pohodlné v telefonu.',
     'default_ru': 'PrometeyLabs делает корпоративные сайты: не конструктор и не чужой шаблон. Это демо — пример того, что вы получаете: страницы, заявки, админка, удобно с телефона.'},
    {'page': 'about', 'key': 'mission', 'type': TEXT, 'label': _('Місія'), 'multiline': True,
     'default': 'Компанія має виглядати серйозно в пошуку й з телефону. Людина заходить — розуміє — залишає заявку.',
     'default_en': 'A company should look serious in search and on the phone. A person arrives — understands — leaves a request.',
     'default_cs': 'Firma má vypadat vážně ve vyhledávání i v telefonu. Člověk přijde — pochopí — nechá poptávku.',
     'default_ru': 'Компания должна выглядеть серьёзно в поиске и с телефона. Человек заходит — понимает — оставляет заявку.'},
    {'page': 'about', 'key': 'photo', 'type': IMAGE, 'label': _('Фото «Про нас»')},

    {'page': 'contacts', 'key': 'address', 'type': TEXT, 'label': _('Адреса'),
     'default': 'Київ, бульвар Тараса Шевченка 46а',
     'default_en': 'Kyiv, Taras Shevchenko Boulevard 46a',
     'default_cs': 'Kyjev, Tarase Ševčenka 46a',
     'default_ru': 'Киев, бульвар Тараса Шевченко 46а'},
    {'page': 'contacts', 'key': 'schedule', 'type': TEXT, 'label': _('Графік роботи'),
     'default': 'Пн–Пт: 10:00–19:00 · консультація за дзвінком',
     'default_en': 'Mon–Fri: 10:00–19:00 · consultation by call',
     'default_cs': 'Po–Pá: 10:00–19:00 · konzultace po hovoru',
     'default_ru': 'Пн–Пт: 10:00–19:00 · консультация по звонку'},
    {'page': 'contacts', 'key': 'phone', 'type': TEXT, 'label': _('Телефон'),
     'default': '+38 (063) 952-05-65', 'default_en': '+38 (063) 952-05-65',
     'default_cs': '+38 (063) 952-05-65', 'default_ru': '+38 (063) 952-05-65'},
    {'page': 'contacts', 'key': 'email', 'type': TEXT, 'label': _('Email'),
     'default': 'info@prometeylabs.com', 'default_en': 'info@prometeylabs.com',
     'default_cs': 'info@prometeylabs.com', 'default_ru': 'info@prometeylabs.com'},

    {'page': 'catalog', 'key': 'title', 'type': TEXT, 'label': _('Заголовок каталогу'),
     'default': 'Приклади корпоративних сайтів',
     'default_en': 'Corporate site examples',
     'default_cs': 'Příklady firemních webů',
     'default_ru': 'Примеры корпоративных сайтов'},
    {'page': 'catalog', 'key': 'buy_cta_label', 'type': TEXT, 'label': _('Текст кнопки «Купити»'),
     'default': 'Хочу такий сайт', 'default_en': 'I want a site like this',
     'default_cs': 'Chci takový web', 'default_ru': 'Хочу такой сайт'},

    {'page': 'cta', 'key': 'title', 'type': TEXT, 'label': _('Заголовок CTA-секції'),
     'default': 'Готові показати компанію сайтом?',
     'default_en': 'Ready to show the company with a site?',
     'default_cs': 'Chcete ukázat firmu webem?',
     'default_ru': 'Готовы показать компанию сайтом?'},
    {'page': 'cta', 'key': 'subtitle', 'type': TEXT, 'label': _('Підпис CTA-секції'), 'multiline': True,
     'default': 'Залиште телефон — покажемо, як виглядатимуть ваші сторінки.',
     'default_en': 'Leave your phone — we will show how your pages will look.',
     'default_cs': 'Nechte telefon — ukážeme, jak budou vaše stránky vypadat.',
     'default_ru': 'Оставьте телефон — покажем, как будут выглядеть ваши страницы.'},
    {'page': 'cta', 'key': 'submit_label', 'type': TEXT, 'label': _('Текст кнопки відправки заявки'),
     'default': 'Залишити заявку', 'default_en': 'Leave a request', 'default_cs': 'Nechat poptávku',
     'default_ru': 'Оставить заявку'},

    {'page': 'footer', 'key': 'partners_visible', 'type': BOOL, 'label': _('Показувати партнерів у футері'),
     'default': '1'},

    {'page': 'seo', 'key': 'title', 'type': TEXT, 'label': _('SEO title'),
     'default': 'PrometeyLabs — корпоративний сайт, з якого пишуть',
     'default_en': 'PrometeyLabs — a corporate site people write from',
     'default_cs': 'PrometeyLabs — firemní web, ze kterého píšou',
     'default_ru': 'PrometeyLabs — корпоративный сайт, с которого пишут'},
    {'page': 'seo', 'key': 'description', 'type': TEXT, 'label': _('SEO description'), 'multiline': True,
     'default': 'Замовте корпоративний сайт: кілька сторінок, заявки, проста адмінка, швидко з телефону. Живий приклад — цей демо.',
     'default_en': 'Order a corporate site: several pages, requests, a simple admin, fast on the phone. This demo is a live example.',
     'default_cs': 'Objednejte firemní web: několik stránek, poptávky, jednoduchý admin, rychle v telefonu. Toto demo je živý příklad.',
     'default_ru': 'Закажите корпоративный сайт: несколько страниц, заявки, простая админка, быстро с телефона. Живой пример — это демо.'},
]
