"""Seed-колекції demo-корпоративного сайту PrometeyLabs (UA/EN/CS/RU)."""

PRODUCTION_STEPS = [
    {
        'title': 'Ви розповідаєте, хто ваша компанія',
        'title_en': 'You tell us who your company is',
        'title_cs': 'Řeknete, kdo je vaše firma',
        'title_ru': 'Вы рассказываете, кто ваша компания',
        'description': 'Короткий дзвінок: кому продаєте, які сторінки потрібні, куди мають падати заявки.',
        'description_en': 'A short call: who you sell to, which pages you need, where requests should go.',
        'description_cs': 'Krátký hovor: komu prodáváte, které stránky potřebujete, kam mají padat poptávky.',
        'description_ru': 'Короткий звонок: кому продаёте, какие страницы нужны, куда должны падать заявки.',
    },
    {
        'title': 'Показуємо структуру сторінок',
        'title_en': 'We show the page structure',
        'title_cs': 'Ukážeme strukturu stránek',
        'title_ru': 'Показываем структуру страниц',
        'description': 'Бачите головну, послуги, про нас і контакти до збірки — без сюрпризів після запуску.',
        'description_en': 'You see home, services, about and contacts before we build — no surprises after launch.',
        'description_cs': 'Uvidíte domů, služby, o nás a kontakty před stavbou — bez překvapení po spuštění.',
        'description_ru': 'Видите главную, услуги, о нас и контакты до сборки — без сюрпризов после запуска.',
    },
    {
        'title': 'Збираємо сайт і підключаємо заявки',
        'title_en': 'We assemble the site and connect requests',
        'title_cs': 'Sestavíme web a napojíme poptávky',
        'title_ru': 'Собираем сайт и подключаем заявки',
        'description': 'Форма, телефон, соцмережі. Заявка з сайту приходить вам — цей демо працює так само.',
        'description_en': 'Form, phone, socials. A request from the site comes to you — this demo works the same way.',
        'description_cs': 'Formulář, telefon, sítě. Poptávka ze webu přijde vám — toto demo funguje stejně.',
        'description_ru': 'Форма, телефон, соцсети. Заявка с сайта приходит вам — это демо работает так же.',
    },
    {
        'title': 'Ви заходите в адмінку й правите самі',
        'title_en': 'You log into the admin and edit yourself',
        'title_cs': 'Vstoupíte do adminu a upravujete sami',
        'title_ru': 'Вы заходите в админку и правите сами',
        'description': 'Тексти, фото й кольори без програміста на кожне «змініть слово».',
        'description_en': 'Texts, photos and colors without a developer for every “change this word”.',
        'description_cs': 'Texty, fotky a barvy bez programátora na každé «změňte slovo».',
        'description_ru': 'Тексты, фото и цвета без программиста на каждое «измените слово».',
    },
]

GALLERY = [
    {'image': 'gallery/site-1.webp', 'kind': 'production',
     'caption': 'Картки, що нахиляються', 'caption_en': 'Cards that tilt',
     'caption_cs': 'Karty, které se naklánějí', 'caption_ru': 'Карточки, которые наклоняются'},
    {'image': 'gallery/site-4.webp', 'kind': 'production',
     'caption': 'Меню, зручне з телефону', 'caption_en': 'A menu that works on the phone',
     'caption_cs': 'Menu pohodlné v telefonu', 'caption_ru': 'Меню, удобное с телефона'},
    {'image': 'gallery/site-5.webp', 'kind': 'production',
     'caption': 'Цифри, що рахуються', 'caption_en': 'Numbers that count up',
     'caption_cs': 'Čísla, která se načítají', 'caption_ru': 'Цифры, которые считаются'},
    {'image': 'gallery/site-6.webp', 'kind': 'production',
     'caption': 'Форма, після якої вам пишуть', 'caption_en': 'A form after which people write to you',
     'caption_cs': 'Formulář, po kterém vám napíšou', 'caption_ru': 'Форма, после которой вам пишут'},
    {'image': 'gallery/admin.webp', 'kind': 'certificate',
     'caption': 'Адмінка, де правите самі', 'caption_en': 'An admin you edit yourself',
     'caption_cs': 'Admin, kde upravujete sami', 'caption_ru': 'Админка, где правите сами'},
    {'image': 'gallery/phone.webp', 'kind': 'certificate',
     'caption': 'Швидко на телефоні', 'caption_en': 'Fast on the phone',
     'caption_cs': 'Rychle v telefonu', 'caption_ru': 'Быстро на телефоне'},
]

TESTIMONIALS = [
    {
        'author_name': 'Олена К.', 'role': 'Клініка, Львів', 'rating': 5,
        'text': 'Люди записуються з сайту. Я більше не пояснюю послуги в Direct по десять разів.',
        'text_en': 'People book from the site. I no longer explain services in Direct ten times.',
        'text_cs': 'Lidé se objednávají z webu. Už desetkrát nevysvětluju služby v Directu.',
        'text_ru': 'Люди записываются с сайта. Я больше не объясняю услуги в Direct по десять раз.',
    },
    {
        'author_name': 'Ігор М.', 'role': 'Виробництво, Київ', 'rating': 5,
        'text': 'Партнери дивляться «Про нас» і одразу пишуть. З телефону все зрозуміло.',
        'text_en': 'Partners look at About and write right away. Everything is clear on the phone.',
        'text_cs': 'Partneři se podívají na O nás a hned napíšou. V telefonu je vše jasné.',
        'text_ru': 'Партнёры смотрят «О нас» и сразу пишут. С телефона всё понятно.',
    },
    {
        'author_name': 'Марина Т.', 'role': 'Агентство', 'rating': 5,
        'text': 'Шість сторінок замість трьох зошитів у Instagram. Заявки в одній адмінці.',
        'text_en': 'Six pages instead of three notebooks in Instagram. Requests in one admin.',
        'text_cs': 'Šest stránek místo tří sešitů na Instagramu. Poptávky v jednom adminu.',
        'text_ru': 'Шесть страниц вместо трёх тетрадей в Instagram. Заявки в одной админке.',
    },
    {
        'author_name': 'Дмитро В.', 'role': 'Будівельна компанія', 'rating': 5,
        'text': 'Тексти міняю сама за хвилину. Реклама менше зливається — сторінка не відлякує.',
        'text_en': 'I change the texts myself in a minute. Ads waste less money — the page does not scare people away.',
        'text_cs': 'Texty měním sama za minutu. Reklama míň utíká — stránka lidi neodrazuje.',
        'text_ru': 'Тексты меняю сама за минуту. Реклама меньше сливается — страница не отпугивает.',
    },
    {
        'author_name': 'Софія Л.', 'role': 'Школа, Харків', 'rating': 5,
        'text': 'Батьки розуміють програми з першого екрана. Запис іде вам, а не губиться в Direct.',
        'text_en': 'Parents understand the programmes from the first screen. Booking comes to you, not lost in Direct.',
        'text_cs': 'Rodiče pochopí programy z první obrazovky. Zápis jde vám, neztratí se v Directu.',
        'text_ru': 'Родители понимают программы с первого экрана. Запись идёт вам, а не теряется в Direct.',
    },
]

PARTNERS = ['Google', 'TikTok', 'Viber', 'YouTube', 'WhatsApp', 'Maps']

CATEGORIES = [
    {
        'name': 'Компанії', 'name_en': 'Companies', 'name_cs': 'Firmy', 'name_ru': 'Компании',
    },
    {
        'name': 'Послуги', 'name_en': 'Services', 'name_cs': 'Služby', 'name_ru': 'Услуги',
    },
    {
        'name': 'Виробництво', 'name_en': 'Production', 'name_cs': 'Výroba', 'name_ru': 'Производство',
    },
    {
        'name': 'Запис і освіта', 'name_en': 'Booking and education',
        'name_cs': 'Objednávky a vzdělávání', 'name_ru': 'Запись и образование',
    },
]

PRODUCTS = [
    {
        'category': 0, 'name': 'Сайт компанії', 'name_en': 'Company site',
        'name_cs': 'Web firmy', 'name_ru': 'Сайт компании',
        'price_from': None,
        'excerpt': 'Головна, про нас, контакти. Компанія виглядає серйозно — заявки йдуть вам.',
        'excerpt_en': 'Home, about, contacts. The company looks serious — requests come to you.',
        'excerpt_cs': 'Domů, o nás, kontakty. Firma vypadá vážně — poptávky jdou vám.',
        'excerpt_ru': 'Главная, о нас, контакты. Компания выглядит серьёзно — заявки идут вам.',
        'specs': 'Сторінки: 5–6\nАдмінка: так\nЗаявки: форма + телефон',
        'specs_en': 'Pages: 5–6\nAdmin: yes\nRequests: form + phone',
        'specs_cs': 'Stránky: 5–6\nAdmin: ano\nPoptávky: formulář + telefon',
        'specs_ru': 'Страницы: 5–6\nАдминка: да\nЗаявки: форма + телефон',
        'image': 'examples/company.webp',
    },
    {
        'category': 0, 'name': 'Багатомовний сайт', 'name_en': 'Multilingual site',
        'name_cs': 'Vícejazyčný web', 'name_ru': 'Многоязычный сайт',
        'price_from': None,
        'excerpt': 'Українська, англійська, чеська, російська. Цей демо так і зібраний.',
        'excerpt_en': 'Ukrainian, English, Czech, Russian. This demo is built that way.',
        'excerpt_cs': 'Ukrajinština, angličtina, čeština, ruština. Toto demo je tak sestavené.',
        'excerpt_ru': 'Украинский, английский, чешский, русский. Это демо так и собрано.',
        'specs': 'Мови: UA / EN / CS / RU\nСторінки: 6+\nАдмінка: так',
        'specs_en': 'Languages: UA / EN / CS / RU\nPages: 6+\nAdmin: yes',
        'specs_cs': 'Jazyky: UA / EN / CS / RU\nStránky: 6+\nAdmin: ano',
        'specs_ru': 'Языки: UA / EN / CS / RU\nСтраницы: 6+\nАдминка: да',
        'image': 'examples/multilingual.webp',
    },
    {
        'category': 1, 'name': 'Сайт з каталогом послуг', 'name_en': 'Site with a services catalog',
        'name_cs': 'Web s katalogem služeb', 'name_ru': 'Сайт с каталогом услуг',
        'price_from': None,
        'excerpt': 'Картки послуг, сторінка кожної, кнопка «хочу так». Як каталог на цьому демо.',
        'excerpt_en': 'Service cards, a page for each, an “I want this” button. Like the catalog on this demo.',
        'excerpt_cs': 'Karty služeb, stránka každé, tlačítko «chci tak». Jako katalog na tomto demu.',
        'excerpt_ru': 'Карточки услуг, страница каждой, кнопка «хочу так». Как каталог на этом демо.',
        'specs': 'Каталог: так\nЗаявка з послуги: так\nАдмінка: так',
        'specs_en': 'Catalog: yes\nRequest from a service: yes\nAdmin: yes',
        'specs_cs': 'Katalog: ano\nPoptávka ze služby: ano\nAdmin: ano',
        'specs_ru': 'Каталог: да\nЗаявка с услуги: да\nАдминка: да',
        'image': 'examples/catalog.webp',
    },
    {
        'category': 1, 'name': 'Сайт агентства', 'name_en': 'Agency site',
        'name_cs': 'Web agentury', 'name_ru': 'Сайт агентства',
        'price_from': None,
        'excerpt': 'Кейси, відгуки, процес роботи. Людина розуміє, з ким має справу.',
        'excerpt_en': 'Cases, reviews, how you work. A person understands who they are dealing with.',
        'excerpt_cs': 'Případy, recenze, jak pracujete. Člověk pochopí, s kým má co do činění.',
        'excerpt_ru': 'Кейсы, отзывы, процесс работы. Человек понимает, с кем имеет дело.',
        'specs': 'Сторінки: про нас + процес\nВідгуки: так\nЗаявки: так',
        'specs_en': 'Pages: about + process\nReviews: yes\nRequests: yes',
        'specs_cs': 'Stránky: o nás + proces\nRecenze: ano\nPoptávky: ano',
        'specs_ru': 'Страницы: о нас + процесс\nОтзывы: да\nЗаявки: да',
        'image': 'examples/agency.webp',
    },
    {
        'category': 2, 'name': 'Сайт виробництва', 'name_en': 'Production site',
        'name_cs': 'Web výroby', 'name_ru': 'Сайт производства',
        'price_from': None,
        'excerpt': 'Етапи, галерея цеху, сертифікати. Партнер бачить, як ви робите — не лише слоган.',
        'excerpt_en': 'Steps, shop-floor gallery, certificates. A partner sees how you work — not just a slogan.',
        'excerpt_cs': 'Kroky, galerie provozu, certifikáty. Partner vidí, jak děláte — nejen slogan.',
        'excerpt_ru': 'Этапы, галерея цеха, сертификаты. Партнёр видит, как вы делаете — не только слоган.',
        'specs': 'Процес: 4 етапи\nГалерея: так\nСертифікати: так',
        'specs_en': 'Process: 4 steps\nGallery: yes\nCertificates: yes',
        'specs_cs': 'Proces: 4 kroky\nGalerie: ano\nCertifikáty: ano',
        'specs_ru': 'Процесс: 4 этапа\nГалерея: да\nСертификаты: да',
        'image': 'examples/production.webp',
    },
    {
        'category': 2, 'name': 'Будівельна компанія', 'name_en': 'Construction company',
        'name_cs': 'Stavební firma', 'name_ru': 'Строительная компания',
        'price_from': None,
        'excerpt': 'Послуги, обʼєкти, заявка на консультацію. З телефону не треба зумити.',
        'excerpt_en': 'Services, projects, a consultation request. No pinching to zoom on the phone.',
        'excerpt_cs': 'Služby, zakázky, poptávka konzultace. V telefonu nemusíte zoomovat.',
        'excerpt_ru': 'Услуги, объекты, заявка на консультацию. С телефона не нужно зумить.',
        'specs': 'Сторінки: послуги + обʼєкти\nЗаявка: так\nМобільний: так',
        'specs_en': 'Pages: services + projects\nRequest: yes\nMobile: yes',
        'specs_cs': 'Stránky: služby + zakázky\nPoptávka: ano\nMobil: ano',
        'specs_ru': 'Страницы: услуги + объекты\nЗаявка: да\nМобильный: да',
        'image': 'examples/construction.webp',
    },
    {
        'category': 3, 'name': 'Сайт клініки', 'name_en': 'Clinic site',
        'name_cs': 'Web kliniky', 'name_ru': 'Сайт клиники',
        'price_from': None,
        'excerpt': 'Послуги, запис, контакти. Заявка приходить вам, а не губиться в месенджері.',
        'excerpt_en': 'Services, booking, contacts. The request comes to you, not lost in a messenger.',
        'excerpt_cs': 'Služby, objednávka, kontakty. Poptávka přijde vám, neztratí se v messengeru.',
        'excerpt_ru': 'Услуги, запись, контакты. Заявка приходит вам, а не теряется в мессенджере.',
        'specs': 'Запис: форма\nПослуги: каталог\nТелефон у шапці: так',
        'specs_en': 'Booking: form\nServices: catalog\nPhone in the header: yes',
        'specs_cs': 'Objednávka: formulář\nSlužby: katalog\nTelefon v hlavičce: ano',
        'specs_ru': 'Запись: форма\nУслуги: каталог\nТелефон в шапке: да',
        'image': 'examples/clinic.webp',
    },
    {
        'category': 3, 'name': 'Сайт школи', 'name_en': 'School site',
        'name_cs': 'Web školy', 'name_ru': 'Сайт школы',
        'price_from': None,
        'excerpt': 'Програми, запис на заняття, філії. Батьки розуміють з першого екрану.',
        'excerpt_en': 'Programmes, class booking, branches. Parents understand from the first screen.',
        'excerpt_cs': 'Programy, zápis na hodiny, pobočky. Rodiče pochopí z první obrazovky.',
        'excerpt_ru': 'Программы, запись на занятия, филиалы. Родители понимают с первого экрана.',
        'specs': 'Сторінки: програми + контакти\nЗапис: так\nМови: за потреби',
        'specs_en': 'Pages: programmes + contacts\nBooking: yes\nLanguages: as needed',
        'specs_cs': 'Stránky: programy + kontakty\nZápis: ano\nJazyky: dle potřeby',
        'specs_ru': 'Страницы: программы + контакты\nЗапись: да\nЯзыки: по необходимости',
        'image': 'examples/school.webp',
    },
]
