"""Дефолтні CMS-блоки demo-лендінгу PrometeyLabs (registry-driven, «Мій лендінг»)."""
from django.utils.translation import gettext_lazy as _

TEXT = 'text'
IMAGE = 'image'
BOOL = 'bool'

PAGE_LABELS = {
    'header': _('Хедер'),
    'hero': _('Hero'),
    'stats': _('Статистика'),
    'offers': _('Послуги'),
    'process': _('Процес роботи'),
    'gallery': _('Галерея'),
    'before_after': _('До / після'),
    'reviews': _('Відгуки'),
    'faq': _('Питання й відповіді'),
    'cta': _('Заклик до дії'),
    'footer': _('Футер'),
    'seo': _('SEO'),
}

BLOCK_REGISTRY = [
    {'page': 'header', 'key': 'company_name', 'type': TEXT, 'label': _('Назва компанії (лого)'),
     'default': 'PrometeyLabs', 'default_en': 'PrometeyLabs', 'default_cs': 'PrometeyLabs',
     'default_ru': 'PrometeyLabs'},
    {'page': 'header', 'key': 'tagline', 'type': TEXT, 'label': _('Підпис біля лого'),
     'default': 'Лендінг, який продає', 'default_en': 'A landing that sells',
     'default_cs': 'Landing, který prodává', 'default_ru': 'Лендинг, который продаёт'},
    {'page': 'header', 'key': 'phone', 'type': TEXT, 'label': _('Телефон у хедері'),
     'default': '+38 (063) 952-05-65', 'default_en': '+38 (063) 952-05-65',
     'default_cs': '+38 (063) 952-05-65', 'default_ru': '+38 (063) 952-05-65'},
    {'page': 'header', 'key': 'instagram_url', 'type': TEXT, 'label': _('Instagram'),
     'default': 'https://instagram.com/prometeylabs',
     'default_en': 'https://instagram.com/prometeylabs',
     'default_cs': 'https://instagram.com/prometeylabs',
     'default_ru': 'https://instagram.com/prometeylabs'},
    {'page': 'header', 'key': 'facebook_url', 'type': TEXT, 'label': _('Facebook'),
     'default': 'https://www.facebook.com/profile.php?id=61577585882254',
     'default_en': 'https://www.facebook.com/profile.php?id=61577585882254',
     'default_cs': 'https://www.facebook.com/profile.php?id=61577585882254',
     'default_ru': 'https://www.facebook.com/profile.php?id=61577585882254'},
    {'page': 'header', 'key': 'telegram_url', 'type': TEXT, 'label': _('Telegram'),
     'default': 'https://t.me/prometeylabs', 'default_en': 'https://t.me/prometeylabs',
     'default_cs': 'https://t.me/prometeylabs', 'default_ru': 'https://t.me/prometeylabs'},

    {'page': 'hero', 'key': 'title', 'type': TEXT, 'label': _('Заголовок hero'), 'multiline': True,
     'default': 'Одна сторінка — і люди залишають заявку',
     'default_en': 'One page — and people leave a request',
     'default_cs': 'Jedna stránka — a lidé nechávají poptávku',
     'default_ru': 'Одна страница — и люди оставляют заявку'},
    {'page': 'hero', 'key': 'subtitle', 'type': TEXT, 'label': _('Підзаголовок hero'), 'multiline': True,
     'default': 'Зрозумілі слова, зручно з телефону, заявки й соцмережі. Тексти потім міняєте самі.',
     'default_en': 'Clear words, easy on the phone, requests and socials. You change the texts yourself later.',
     'default_cs': 'Srozumitelná slova, pohodlné v telefonu, poptávky a sítě. Texty pak měníte sami.',
     'default_ru': 'Понятные слова, удобно с телефона, заявки и соцсети. Тексты потом меняете сами.'},
    {'page': 'hero', 'key': 'cta_label', 'type': TEXT, 'label': _('Текст кнопки hero'),
     'default': 'Хочу такий лендінг', 'default_en': 'I want a landing like this',
     'default_cs': 'Chci takový landing', 'default_ru': 'Хочу такой лендинг'},

    {'page': 'stats', 'key': 'stats_visible', 'type': BOOL, 'label': _('Показувати статистику'),
     'default': '1'},
    {'page': 'stats', 'key': 'stat_projects', 'type': TEXT, 'label': _('Статистика: днів до старту'),
     'default': '7', 'default_en': '7', 'default_cs': '7', 'default_ru': '7'},
    {'page': 'stats', 'key': 'stat_years', 'type': TEXT, 'label': _('Статистика: сторінок'),
     'default': '1', 'default_en': '1', 'default_cs': '1', 'default_ru': '1'},
    {'page': 'stats', 'key': 'stat_clients', 'type': TEXT, 'label': _('Статистика: години заявок'),
     'default': '24', 'default_en': '24', 'default_cs': '24', 'default_ru': '24'},
    {'page': 'stats', 'key': 'stat_warranty', 'type': TEXT, 'label': _('Статистика: зручно з телефону'),
     'default': '100', 'default_en': '100', 'default_cs': '100', 'default_ru': '100'},

    {'page': 'offers', 'key': 'offers_visible', 'type': BOOL, 'label': _('Показувати послуги'),
     'default': '1'},
    {'page': 'offers', 'key': 'title', 'type': TEXT, 'label': _('Заголовок секції послуг'),
     'default': 'Що ви отримаєте', 'default_en': 'What you get', 'default_cs': 'Co získáte',
     'default_ru': 'Что вы получите'},

    {'page': 'process', 'key': 'process_visible', 'type': BOOL, 'label': _('Показувати процес роботи'),
     'default': '1'},
    {'page': 'process', 'key': 'title', 'type': TEXT, 'label': _('Заголовок процесу'),
     'default': 'Як ми робимо лендінг', 'default_en': 'How we make a landing',
     'default_cs': 'Jak děláme landing', 'default_ru': 'Как мы делаем лендинг'},
    {'page': 'process', 'key': 'step_1', 'type': TEXT, 'label': _('Крок 1'),
     'default': 'Ви розповідаєте, хто ваш клієнт',
     'default_en': 'You tell us who your client is',
     'default_cs': 'Řeknete, kdo je váš klient',
     'default_ru': 'Вы рассказываете, кто ваш клиент'},
    {'page': 'process', 'key': 'step_2', 'type': TEXT, 'label': _('Крок 2'),
     'default': 'Показуємо, як виглядатиме сторінка',
     'default_en': 'We show how the page will look',
     'default_cs': 'Ukážeme, jak bude stránka vypadat',
     'default_ru': 'Показываем, как будет выглядеть страница'},
    {'page': 'process', 'key': 'step_3', 'type': TEXT, 'label': _('Крок 3'),
     'default': 'Збираємо лендінг і підключаємо заявки',
     'default_en': 'We assemble the landing and connect requests',
     'default_cs': 'Sestavíme landing a napojíme poptávky',
     'default_ru': 'Собираем лендинг и подключаем заявки'},
    {'page': 'process', 'key': 'step_4', 'type': TEXT, 'label': _('Крок 4'),
     'default': 'Ви заходите в адмінку й правите самі',
     'default_en': 'You log into the admin and edit yourself',
     'default_cs': 'Vstoupíte do adminu a upravujete sami',
     'default_ru': 'Вы заходите в админку и правите сами'},

    {'page': 'gallery', 'key': 'gallery_visible', 'type': BOOL, 'label': _('Показувати галерею'),
     'default': '1'},
    {'page': 'gallery', 'key': 'title', 'type': TEXT, 'label': _('Заголовок галереї'),
     'default': 'Живі ефекти, не мертва картинка',
     'default_en': 'Live effects, not a dead picture',
     'default_cs': 'Živé efekty, ne mrtvý obrázek',
     'default_ru': 'Живые эффекты, не мёртвая картинка'},

    {'page': 'before_after', 'key': 'before_after_visible', 'type': BOOL, 'label': _('Показувати «до/після»'),
     'default': '1'},
    {'page': 'before_after', 'key': 'title', 'type': TEXT, 'label': _('Заголовок «до/після»'),
     'default': 'Конструктор і живий лендінг',
     'default_en': 'A builder site and a live landing',
     'default_cs': 'Konstruktor a živý landing',
     'default_ru': 'Конструктор и живой лендинг'},

    {'page': 'reviews', 'key': 'reviews_visible', 'type': BOOL, 'label': _('Показувати відгуки'),
     'default': '1'},
    {'page': 'reviews', 'key': 'title', 'type': TEXT, 'label': _('Заголовок відгуків'),
     'default': 'Люди, які вже замовили', 'default_en': 'People who already ordered',
     'default_cs': 'Lidé, kteří už objednali', 'default_ru': 'Люди, которые уже заказали'},

    {'page': 'faq', 'key': 'faq_visible', 'type': BOOL, 'label': _('Показувати FAQ'),
     'default': '1'},
    {'page': 'faq', 'key': 'title', 'type': TEXT, 'label': _('Заголовок FAQ'),
     'default': 'Питання й відповіді', 'default_en': 'Questions and answers',
     'default_cs': 'Otázky a odpovědi', 'default_ru': 'Вопросы и ответы'},
    {'page': 'faq', 'key': 'faq_1_q', 'type': TEXT, 'label': _('FAQ 1: питання'),
     'default': 'Чим це краще за конструктор?',
     'default_en': 'How is this better than a website builder?',
     'default_cs': 'Čím je to lepší než konstruktor?',
     'default_ru': 'Чем это лучше конструктора?'},
    {'page': 'faq', 'key': 'faq_1_a', 'type': TEXT, 'label': _('FAQ 1: відповідь'), 'multiline': True,
     'default': 'Немає щомісячної плати й чужого шаблону. Сторінка ваша, швидка, без зайвих кнопок.',
     'default_en': 'No monthly fee and no someone else’s template. The page is yours, fast, without extra buttons.',
     'default_cs': 'Žádný měsíční poplatek a cizí šablona. Stránka je vaše, rychlá, bez zbytečných tlačítek.',
     'default_ru': 'Нет ежемесячной платы и чужого шаблона. Страница ваша, быстрая, без лишних кнопок.'},
    {'page': 'faq', 'key': 'faq_2_q', 'type': TEXT, 'label': _('FAQ 2: питання'),
     'default': 'Я зміню текст без програміста?',
     'default_en': 'Can I change the text without a developer?',
     'default_cs': 'Změním text bez programátora?',
     'default_ru': 'Я изменю текст без программиста?'},
    {'page': 'faq', 'key': 'faq_2_a', 'type': TEXT, 'label': _('FAQ 2: відповідь'), 'multiline': True,
     'default': 'Так. Відкрили адмінку — змінили — зберегли.',
     'default_en': 'Yes. Open the admin — change — save.',
     'default_cs': 'Ano. Otevřete admin — změníte — uložíte.',
     'default_ru': 'Да. Открыли админку — изменили — сохранили.'},
    {'page': 'faq', 'key': 'faq_3_q', 'type': TEXT, 'label': _('FAQ 3: питання'),
     'default': 'Скільки чекати?',
     'default_en': 'How long to wait?',
     'default_cs': 'Jak dlouho čekat?',
     'default_ru': 'Сколько ждать?'},
    {'page': 'faq', 'key': 'faq_3_a', 'type': TEXT, 'label': _('FAQ 3: відповідь'), 'multiline': True,
     'default': 'Зазвичай кілька днів. Точніше скажемо після короткого дзвінка.',
     'default_en': 'Usually a few days. We will say more precisely after a short call.',
     'default_cs': 'Obvykle několik dní. Přesněji řekneme po krátkém hovoru.',
     'default_ru': 'Обычно несколько дней. Точнее скажем после короткого звонка.'},

    {'page': 'cta', 'key': 'title', 'type': TEXT, 'label': _('Заголовок CTA-секції'),
     'default': 'Готові отримувати заявки?', 'default_en': 'Ready to get requests?',
     'default_cs': 'Chcete dostávat poptávky?', 'default_ru': 'Готовы получать заявки?'},
    {'page': 'cta', 'key': 'subtitle', 'type': TEXT, 'label': _('Підпис CTA-секції'), 'multiline': True,
     'default': 'Залиште телефон — покажемо, як виглядатиме ваша сторінка.',
     'default_en': 'Leave your phone — we will show how your page will look.',
     'default_cs': 'Nechte telefon — ukážeme, jak bude vaše stránka vypadat.',
     'default_ru': 'Оставьте телефон — покажем, как будет выглядеть ваша страница.'},
    {'page': 'cta', 'key': 'submit_label', 'type': TEXT, 'label': _('Текст кнопки відправки заявки'),
     'default': 'Залишити заявку', 'default_en': 'Leave a request', 'default_cs': 'Nechat poptávku',
     'default_ru': 'Оставить заявку'},
    {'page': 'cta', 'key': 'image', 'type': IMAGE, 'label': _('Фото поруч із формою')},

    {'page': 'footer', 'key': 'partners_visible', 'type': BOOL, 'label': _('Показувати партнерів'),
     'default': '1'},
    {'page': 'footer', 'key': 'address', 'type': TEXT, 'label': _('Адреса'),
     'default': 'Київ, бульвар Тараса Шевченка 46а',
     'default_en': 'Kyiv, Taras Shevchenko Boulevard 46a',
     'default_cs': 'Kyjev, Tarase Ševčenka 46a',
     'default_ru': 'Киев, бульвар Тараса Шевченко 46а'},

    {'page': 'seo', 'key': 'title', 'type': TEXT, 'label': _('SEO title'),
     'default': 'PrometeyLabs — лендінг, який продає',
     'default_en': 'PrometeyLabs — a landing that sells',
     'default_cs': 'PrometeyLabs — landing, který prodává',
     'default_ru': 'PrometeyLabs — лендинг, который продаёт'},
    {'page': 'seo', 'key': 'description', 'type': TEXT, 'label': _('SEO description'), 'multiline': True,
     'default': 'Замовте лендінг: потрібні блоки, заявки, соцмережі, проста адмінка, швидка сторінка з телефону.',
     'default_en': 'Order a landing: the blocks you need, requests, socials, a simple admin, a fast page on the phone.',
     'default_cs': 'Objednejte landing: potřebné bloky, poptávky, sítě, jednoduchý admin, rychlá stránka v telefonu.',
     'default_ru': 'Закажите лендинг: нужные блоки, заявки, соцсети, простая админка, быстрая страница с телефона.'},
]
