# Generated by Django 4.2.21 on 2026-09-06 12:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_proposal_kind_and_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('name_ru', models.CharField(blank=True, max_length=150, verbose_name='Назва (RU)')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='Назва (EN)')),
                ('name_cs', models.CharField(blank=True, max_length=150, verbose_name='Назва (CS)')),
                ('slug', models.SlugField(allow_unicode=True, max_length=160, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категорія каталогу',
                'verbose_name_plural': 'Категорії каталогу',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CorpProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Назва (RU)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Назва (EN)')),
                ('name_cs', models.CharField(blank=True, max_length=200, verbose_name='Назва (CS)')),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, verbose_name='Короткий опис')),
                ('excerpt_ru', models.TextField(blank=True, verbose_name='Короткий опис (RU)')),
                ('excerpt_en', models.TextField(blank=True, verbose_name='Короткий опис (EN)')),
                ('excerpt_cs', models.TextField(blank=True, verbose_name='Короткий опис (CS)')),
                ('specs', models.TextField(blank=True, verbose_name='Характеристики')),
                ('specs_ru', models.TextField(blank=True, verbose_name='Характеристики (RU)')),
                ('specs_en', models.TextField(blank=True, verbose_name='Характеристики (EN)')),
                ('specs_cs', models.TextField(blank=True, verbose_name='Характеристики (CS)')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна від')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Популярний')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='democorp.corpcategory', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар каталогу',
                'verbose_name_plural': 'Товари каталогу',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CorpSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, max_length=160, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Вимкнено — вітрина й адмінка клієнта повертають 404', verbose_name='Активний')),
                ('demo_login', models.CharField(blank=True, max_length=150, verbose_name='Логін (демо)')),
                ('demo_password', models.CharField(blank=True, help_text='Показується лише в цій адмінці — для передачі клієнту', max_length=150, verbose_name='Пароль (демо)')),
                ('color_primary', models.CharField(blank=True, help_text='Hex, напр. #D6CEC7. Порожньо = дефолт', max_length=7, validators=[django.core.validators.RegexValidator(message='Формат кольору: #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Основний колір')),
                ('color_primary_hover', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Формат кольору: #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Основний колір (hover)')),
                ('color_accent', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Формат кольору: #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Акцентний колір')),
                ('color_surface', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Формат кольору: #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Фон секцій')),
                ('color_text', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Формат кольору: #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір тексту')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('style_preset', models.CharField(choices=[('editorial', 'Editorial (paper + ink)'), ('clean', 'Clean (світлий, синій акцент)')], default='editorial', max_length=20, verbose_name='Стиль')),
                ('has_catalog', models.BooleanField(default=False, help_text='Без оплат/кошика — кнопка «Купити» відкриває заявку', verbose_name='Каталог продукції')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='democorp/hero/', verbose_name='Hero — фото')),
                ('owner_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_corp', to=settings.AUTH_USER_MODEL, verbose_name='Клієнтський логін')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_corp', to='core.proposal', verbose_name='Комерційна пропозиція')),
            ],
            options={
                'verbose_name': 'Демо-сайт (корпоративний)',
                'verbose_name_plural': 'Демо-сайти (корпоративні)',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CorpTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150, verbose_name='Автор')),
                ('role', models.CharField(blank=True, max_length=150, verbose_name='Компанія / проєкт')),
                ('text', models.TextField(verbose_name='Текст')),
                ('text_ru', models.TextField(blank=True, verbose_name='Текст (RU)')),
                ('text_en', models.TextField(blank=True, verbose_name='Текст (EN)')),
                ('text_cs', models.TextField(blank=True, verbose_name='Текст (CS)')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оцінка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='democorp.corpsite', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CorpProductionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва етапу')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Назва (RU)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Назва (EN)')),
                ('title_cs', models.CharField(blank=True, max_length=200, verbose_name='Назва (CS)')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('description_ru', models.TextField(blank=True, verbose_name='Опис (RU)')),
                ('description_en', models.TextField(blank=True, verbose_name='Опис (EN)')),
                ('description_cs', models.TextField(blank=True, verbose_name='Опис (CS)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_steps', to='democorp.corpsite', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Етап виробництва',
                'verbose_name_plural': 'Етапи виробництва',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CorpProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='democorp/products/', verbose_name='Фото')),
                ('is_main', models.BooleanField(default=False, verbose_name='Головне фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='democorp.corpproduct', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товару',
                'verbose_name_plural': 'Фото товару',
                'ordering': ('-is_main', 'order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='corpproduct',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='democorp.corpsite', verbose_name='Сайт'),
        ),
        migrations.CreateModel(
            name='CorpPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва (профільна система)')),
                ('logo', models.ImageField(upload_to='democorp/partners/', verbose_name='Лого')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='democorp.corpsite', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнери',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CorpLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Імʼя')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='democorp.corpproduct', verbose_name='Товар (якщо «Купити»)')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='democorp.corpsite', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CorpGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='democorp/gallery/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Підпис')),
                ('caption_ru', models.CharField(blank=True, max_length=200, verbose_name='Підпис (RU)')),
                ('caption_en', models.CharField(blank=True, max_length=200, verbose_name='Підпис (EN)')),
                ('caption_cs', models.CharField(blank=True, max_length=200, verbose_name='Підпис (CS)')),
                ('kind', models.CharField(choices=[('production', 'Цех / виробництво'), ('certificate', 'Сертифікат')], default='production', max_length=12, verbose_name='Тип')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='democorp.corpsite', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Фото галереї',
                'verbose_name_plural': 'Галерея / сертифікати',
                'ordering': ('kind', 'order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='corpcategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='democorp.corpsite', verbose_name='Сайт'),
        ),
        migrations.AlterUniqueTogether(
            name='corpproduct',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='corpcategory',
            unique_together={('tenant', 'slug')},
        ),
        migrations.CreateModel(
            name='CorpBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(db_index=True, max_length=40, verbose_name='Сторінка')),
                ('key', models.CharField(max_length=60, verbose_name='Ключ')),
                ('block_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Зображення'), ('bool', 'Перемикач (видимість секції)')], default='text', max_length=10, verbose_name='Тип')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='Підпис для адмінки')),
                ('value_text', models.TextField(blank=True, verbose_name='Текст')),
                ('value_text_ru', models.TextField(blank=True, verbose_name='Текст (RU)')),
                ('value_text_en', models.TextField(blank=True, verbose_name='Текст (EN)')),
                ('value_text_cs', models.TextField(blank=True, verbose_name='Текст (CS)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('value_image', models.ImageField(blank=True, null=True, upload_to='democorp/blocks/', verbose_name='Зображення')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='democorp.corpsite', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Блок контенту',
                'verbose_name_plural': 'Блоки контенту',
                'ordering': ('page', 'order', 'id'),
                'unique_together': {('tenant', 'page', 'key')},
            },
        ),
    ]
