# Generated by Django 4.2.21 on 2026-09-02 18:47

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_portfolioproject_cta'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, help_text='URL: /demo/<slug>/ — генерується автоматично, невгадуваний', max_length=160, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=200, verbose_name='Назва магазину')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Вимкнено — вітрина й адмінка клієнта повертають 404', verbose_name='Активний')),
                ('demo_login', models.CharField(blank=True, max_length=150, verbose_name='Логін (демо)')),
                ('demo_password', models.CharField(blank=True, help_text='Показується лише в цій адмінці — для передачі клієнту', max_length=150, verbose_name='Пароль (демо)')),
                ('color_primary', models.CharField(blank=True, help_text='Hex, напр. #E65100. Порожньо = дефолт', max_length=7, validators=[django.core.validators.RegexValidator(message='Формат кольору: #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Основний колір')),
                ('color_primary_hover', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Формат кольору: #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Основний колір (hover)')),
                ('color_accent', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Формат кольору: #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Акцентний колір')),
                ('color_surface', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Формат кольору: #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Фон секцій')),
                ('color_text', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Формат кольору: #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір тексту')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('owner_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_shop', to=settings.AUTH_USER_MODEL, verbose_name='Клієнтський логін')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_shop', to='core.proposal', verbose_name='Комерційна пропозиція')),
            ],
            options={
                'verbose_name': 'Демо-магазин',
                'verbose_name_plural': 'Демо-магазини',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Назва')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=140, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, max_length=8, verbose_name='Іконка (emoji)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='demoshop.demoshop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ('order', 'name'),
                'unique_together': {('shop', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Клієнт')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адреса доставки')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('confirmed', 'Підтверджено'), ('done', 'Виконано')], default='new', max_length=12, verbose_name='Статус')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сума')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='demoshop.demoshop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, max_length=240, verbose_name='Короткий опис')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Ціна')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стара ціна')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Хіт')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='demoshop.shopcategory', verbose_name='Категорія')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='demoshop.demoshop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ('order', '-created_at'),
                'unique_together': {('shop', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ShopReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=120, verbose_name='Автор')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оцінка')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='demoshop.shopproduct', verbose_name='Товар')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='demoshop.demoshop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ShopProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='demoshop/products/', verbose_name='Фото')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Alt-текст')),
                ('is_main', models.BooleanField(default=False, verbose_name='Головне фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='demoshop.shopproduct', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товару',
                'verbose_name_plural': 'Фото товару',
                'ordering': ('-is_main', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ShopOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Назва (знімок)')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Ціна (знімок)')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='demoshop.shoporder', verbose_name='Замовлення')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demoshop.shopproduct', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
            },
        ),
        migrations.CreateModel(
            name='ShopHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='demoshop/hero/', verbose_name='Фото')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок')),
                ('cta_label', models.CharField(blank=True, max_length=80, verbose_name='Текст кнопки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='demoshop.demoshop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Слайд головної',
                'verbose_name_plural': 'Слайди головної',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ShopBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(db_index=True, max_length=40, verbose_name='Сторінка')),
                ('key', models.CharField(max_length=60, verbose_name='Ключ')),
                ('block_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Зображення')], default='text', max_length=10, verbose_name='Тип')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='Підпис для адмінки')),
                ('value_text', models.TextField(blank=True, verbose_name='Текст')),
                ('value_image', models.ImageField(blank=True, null=True, upload_to='demoshop/blocks/', verbose_name='Зображення')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='demoshop.demoshop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Блок контенту',
                'verbose_name_plural': 'Блоки контенту',
                'ordering': ('page', 'order', 'id'),
                'unique_together': {('shop', 'page', 'key')},
            },
        ),
    ]
