# Generated by Django 4.2.21 on 2026-09-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoshop', '0002_democlient_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='delivery_method',
            field=models.CharField(choices=[('np_warehouse', 'Відділення Нової Пошти'), ('address', 'Адресна доставка')], default='np_warehouse', max_length=20, verbose_name='Спосіб доставки'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='np_city_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Місто НП'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='np_city_ref',
            field=models.CharField(blank=True, max_length=64, verbose_name='Ref міста НП'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='np_warehouse_name',
            field=models.CharField(blank=True, max_length=512, verbose_name='Відділення НП'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='np_warehouse_ref',
            field=models.CharField(blank=True, max_length=64, verbose_name='Ref відділення НП'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='gift_promo_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подарунок до замовлення'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='sale_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Кінець акції (таймер)'),
        ),
    ]
