# Generated by Django 4.2.21 on 2026-09-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoshop', '0003_sale_timer_gift_np_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopblock',
            name='value_text_en',
            field=models.TextField(blank=True, verbose_name='Текст (EN)'),
        ),
        migrations.AddField(
            model_name='shopblock',
            name='value_text_ru',
            field=models.TextField(blank=True, verbose_name='Текст (RU)'),
        ),
        migrations.AddField(
            model_name='shopcategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Назва (EN)'),
        ),
        migrations.AddField(
            model_name='shopcategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=120, verbose_name='Назва (RU)'),
        ),
        migrations.AddField(
            model_name='shopheroslide',
            name='cta_label_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='Текст кнопки (EN)'),
        ),
        migrations.AddField(
            model_name='shopheroslide',
            name='cta_label_ru',
            field=models.CharField(blank=True, max_length=80, verbose_name='Текст кнопки (RU)'),
        ),
        migrations.AddField(
            model_name='shopheroslide',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок (EN)'),
        ),
        migrations.AddField(
            model_name='shopheroslide',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок (RU)'),
        ),
        migrations.AddField(
            model_name='shopheroslide',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='shopheroslide',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='address_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адреса доставки (EN)'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='address_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адреса доставки (RU)'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='np_city_name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Місто НП (EN)'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='np_city_name_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Місто НП (RU)'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='np_warehouse_name_en',
            field=models.CharField(blank=True, max_length=512, verbose_name='Відділення НП (EN)'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='np_warehouse_name_ru',
            field=models.CharField(blank=True, max_length=512, verbose_name='Відділення НП (RU)'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Опис (EN)'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Опис (RU)'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='gift_promo_text_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подарунок до замовлення (EN)'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='gift_promo_text_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подарунок до замовлення (RU)'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Назва (EN)'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Назва (RU)'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=240, verbose_name='Короткий опис (EN)'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='short_description_ru',
            field=models.CharField(blank=True, max_length=240, verbose_name='Короткий опис (RU)'),
        ),
    ]
