# Generated by Django 5.x on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoshop', '0004_shopblock_value_text_en_shopblock_value_text_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopheroslide',
            name='image',
            field=models.ImageField(upload_to='demoshop/hero/', verbose_name='Фото (широке)'),
        ),
        migrations.AddField(
            model_name='shopheroslide',
            name='image_narrow',
            field=models.ImageField(
                blank=True,
                upload_to='demoshop/hero/',
                verbose_name='Фото (вузьке / мобільне)',
            ),
        ),
    ]
