# Generated by Django 4.2.21 on 2026-09-05 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoshop', '0005_shopheroslide_image_narrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopblock',
            name='value_text_cs',
            field=models.TextField(blank=True, verbose_name='Текст (CS)'),
        ),
        migrations.AddField(
            model_name='shopcategory',
            name='name_cs',
            field=models.CharField(blank=True, max_length=120, verbose_name='Назва (CS)'),
        ),
        migrations.AddField(
            model_name='shopheroslide',
            name='cta_label_cs',
            field=models.CharField(blank=True, max_length=80, verbose_name='Текст кнопки (CS)'),
        ),
        migrations.AddField(
            model_name='shopheroslide',
            name='subtitle_cs',
            field=models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок (CS)'),
        ),
        migrations.AddField(
            model_name='shopheroslide',
            name='title_cs',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (CS)'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='address_cs',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адреса доставки (CS)'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='np_city_name_cs',
            field=models.CharField(blank=True, max_length=255, verbose_name='Місто НП (CS)'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='np_warehouse_name_cs',
            field=models.CharField(blank=True, max_length=512, verbose_name='Відділення НП (CS)'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='description_cs',
            field=models.TextField(blank=True, verbose_name='Опис (CS)'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='gift_promo_text_cs',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подарунок до замовлення (CS)'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='name_cs',
            field=models.CharField(blank=True, max_length=200, verbose_name='Назва (CS)'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='short_description_cs',
            field=models.CharField(blank=True, max_length=240, verbose_name='Короткий опис (CS)'),
        ),
        migrations.AlterField(
            model_name='demoshop',
            name='color_primary',
            field=models.CharField(blank=True, help_text='Hex, напр. #D6CEC7. Порожньо = дефолт', max_length=7, validators=[django.core.validators.RegexValidator(message='Формат кольору: #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Основний колір'),
        ),
    ]
