#!/usr/bin/env python3
"""Concatenate homepage page_css sources into static/css/home-page-bundle.css.

Order must match templates/pages/home.html (DEBUG branch). Do not include
base-bundle.css or fonts.css — those load separately.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STATIC_CSS = ROOT / "static" / "css"
OUT = STATIC_CSS / "home-page-bundle.css"

SOURCES = [
    "home.css",
    "components/marquee-why-choose.css",
    "home-redesign/home-redesign-v2.css",
    "home-redesign/home-redesign-v3.css",
    "home-redesign/home-redesign-final.css",
    "home-redesign/home-redesign-bridge.css",
    "home-redesign/home-why-cards.css",
    "process_block.css",
    "services_piano_block.css",
    "services_piano_block_mob.css",
    "services_piano_video.css",
    "home-motion.css",
]


def main() -> None:
    parts: list[str] = [
        "/* AUTO-GENERATED by scripts/build_home_css.py — do not edit by hand. */\n"
        "/* Source order matches templates/pages/home.html DEBUG page_css. */\n"
    ]
    for rel in SOURCES:
        path = STATIC_CSS / rel
        if not path.is_file():
            raise SystemExit(f"Missing CSS source: {path}")
        parts.append(f"\n/* ===== {rel} ===== */\n")
        parts.append(path.read_text(encoding="utf-8"))
        if not parts[-1].endswith("\n"):
            parts.append("\n")

    OUT.write_text("".join(parts), encoding="utf-8")
    size = OUT.stat().st_size
    print(f"Wrote {OUT.relative_to(ROOT)} ({size / 1024:.1f} KiB) from {len(SOURCES)} files")


if __name__ == "__main__":
    main()
