"""Нові проєкти портфоліо — лендинги, корпоративні, PWA (частина 3)."""
from apps.core.portfolio_seed_helpers import CORP_TAGS, LANDING_TAGS, card

PORTFOLIO_PROJECTS_3 = [
    card(
        slug='auction-center',
        title='Центр земельних аукціонів',
        subtitle='ЗЕМЕЛЬНІ АУКЦІОНИ',
        title_ru='Центр земельных аукционов',
        subtitle_ru='ЗЕМЕЛЬНЫЕ АУКЦИОНЫ',
        desc='Лендінг центру земельних аукціонів: послуги торгів, заявка та контакти організатора.',
        desc_ru='Лендинг центра земельных аукционов: услуги торгов, заявка и контакты организатора.',
        tags=LANDING_TAGS,
        site_url='https://www.auction-center.com.ua/',
        order=12,
    ),
    card(
        slug='elit-fasad',
        title='Еліт-фасад девелопмент',
        subtitle='БУДІВНИЦТВО',
        title_ru='Элит-фасад девелопмент',
        subtitle_ru='СТРОИТЕЛЬСТВО',
        desc='Лендінг будівельної компанії: фасадні та девелоперські послуги, заявка на прорахунок.',
        desc_ru='Лендинг строительной компании: фасадные и девелоперские услуги, заявка на расчёт.',
        tags=LANDING_TAGS,
        site_url='https://elit-fasad-development.com.ua/',
        order=6,
    ),
    card(
        slug='distageavto',
        title='DISTAGEavto',
        subtitle='ЧІП-ТЮНІНГ',
        title_ru='DISTAGEavto',
        subtitle_ru='ЧИП-ТЮНИНГ',
        desc='Лендінг студії чіп-тюнінгу: послуги прошивки, заявка та контакти сервісу.',
        desc_ru='Лендинг студии чип-тюнинга: услуги прошивки, заявка и контакты сервиса.',
        tags=LANDING_TAGS,
        site_url='https://www.distageavto.com/uk/',
        order=15,
    ),
    card(
        slug='grand-oblik',
        title='Гранд Облік',
        subtitle='БУХГАЛТЕРСЬКІ ПОСЛУГИ',
        title_ru='Гранд Учёт',
        subtitle_ru='БУХГАЛТЕРСКИЕ УСЛУГИ',
        desc='Лендінг бухгалтерських послуг: супровід обліку, заявка на консультацію, контакти.',
        desc_ru='Лендинг бухгалтерских услуг: сопровождение учёта, заявка на консультацию, контакты.',
        tags=LANDING_TAGS,
        site_url='https://grand-oblik.com.ua/',
        order=16,
    ),
    card(
        slug='evropobuts',
        title='Європобут С',
        subtitle='БУДІВНИЦТВО',
        title_ru='Европобут С',
        subtitle_ru='СТРОИТЕЛЬСТВО',
        desc='Лендінг будівельної компанії: побутові та будівельні послуги, заявка, контакти.',
        desc_ru='Лендинг строительной компании: бытовые и строительные услуги, заявка, контакты.',
        tags=LANDING_TAGS,
        site_url='https://evropobuts.com.ua/',
        order=13,
    ),
    card(
        slug='fanera',
        title='Фанера',
        subtitle='БУДІВЕЛЬНІ ПЛИТИ',
        title_ru='Фанера',
        subtitle_ru='СТРОИТЕЛЬНЫЕ ПЛИТЫ',
        desc='Лендінг постачальника фанери та плит: асортимент, заявка на прорахунок, доставка.',
        desc_ru='Лендинг поставщика фанеры и плит: ассортимент, заявка на расчёт, доставка.',
        tags=LANDING_TAGS,
        site_url='https://faneradvp.com/',
        order=41,
    ),
    card(
        slug='molodii',
        title='Молодій Тетяна',
        subtitle='ПСИХОЛОГ',
        title_ru='Молодий Татьяна',
        subtitle_ru='ПСИХОЛОГ',
        desc='Лендінг психолога Тетяни Молодій: про підхід, запис на консультацію, контакти.',
        desc_ru='Лендинг психолога Татьяны Молодий: о подходе, запись на консультацию, контакты.',
        tags=LANDING_TAGS,
        site_url='https://molodiitetiana.com/',
        order=94,
        show_on_portfolio=False,
    ),
    card(
        slug='aniloks',
        title='Анілокс',
        subtitle='ОБЛАДНАННЯ ДЛЯ ДРУКУ',
        title_ru='Анилокс',
        subtitle_ru='ОБОРУДОВАНИЕ ДЛЯ ПЕЧАТИ',
        desc='Лендінг постачальника анілоксів і обладнання для друку: каталог, заявка, контакти.',
        desc_ru='Лендинг поставщика анилоксов и оборудования для печати: каталог, заявка, контакты.',
        tags=LANDING_TAGS,
        site_url='https://www.aniloks.com.ua/',
        order=42,
    ),
    card(
        slug='queendrive',
        title='Queen Drive',
        subtitle='АВТОШКОЛА',
        title_ru='Queen Drive',
        subtitle_ru='АВТОШКОЛА',
        desc='Лендінг автошколи: курси водіння, заявка на навчання, контакти.',
        desc_ru='Лендинг автошколы: курсы вождения, заявка на обучение, контакты.',
        tags=LANDING_TAGS,
        site_url='https://queendrive.com.ua/',
        order=18,
    ),
    card(
        slug='choboty',
        title='bolotovashoes',
        subtitle='ВЗУТТЯ',
        title_ru='bolotovashoes',
        subtitle_ru='ОБУВЬ',
        desc='Лендінг бренду взуття: колекції, заявка / замовлення, контакти магазину.',
        desc_ru='Лендинг бренда обуви: коллекции, заявка / заказ, контакты магазина.',
        tags=LANDING_TAGS,
        site_url='https://choboty.store/',
        order=43,
    ),
    card(
        slug='maison-polina',
        title='Maison Polina',
        subtitle='КОМПАНЬЙОН',
        title_ru='Maison Polina',
        subtitle_ru='КОМПАНЬОН',
        desc='Лендінг сервісу компаньйона: формат супроводу, заявка, контакти.',
        desc_ru='Лендинг сервиса компаньона: формат сопровождения, заявка, контакты.',
        tags=LANDING_TAGS,
        site_url='https://maisonpolina.com.ua/',
        order=22,
    ),
    card(
        slug='zelin',
        title='Zelin',
        subtitle='ЗАХИСТ ПЛИТКИ',
        title_ru='Zelin',
        subtitle_ru='ЗАЩИТА ПЛИТКИ',
        desc='Лендінг засобів захисту плитки: продукт, заявка, контакти виробника.',
        desc_ru='Лендинг средств защиты плитки: продукт, заявка, контакты производителя.',
        tags=LANDING_TAGS,
        site_url='https://zelin.com.ua/',
        order=44,
    ),
    card(
        slug='speak-up',
        title='Speak Up',
        subtitle='ШКОЛА АНГЛІЙСЬКОЇ',
        title_ru='Speak Up',
        subtitle_ru='ШКОЛА АНГЛИЙСКОГО',
        desc='Корпоративний сайт школи англійської: програми, запис на заняття, контакти філій.',
        desc_ru='Корпоративный сайт школы английского: программы, запись на занятия, контакты филиалов.',
        tags=CORP_TAGS,
        site_url='https://speak-up.com.ua/',
        order=95,
        show_on_portfolio=False,
    ),
    card(
        slug='kanalizacia',
        title='Прочищення каналізації Дніпро',
        subtitle='ПРОЧИЩЕННЯ КАНАЛІЗАЦІЇ',
        title_ru='Прочистка канализации Днепр',
        subtitle_ru='ПРОЧИСТКА КАНАЛИЗАЦИИ',
        desc='Корпоративний сайт аварійної служби: прочищення каналізації, заявка, виїзд у Дніпрі.',
        desc_ru='Корпоративный сайт аварийной службы: прочистка канализации, заявка, выезд в Днепре.',
        tags=CORP_TAGS,
        site_url='https://kanalizacia-dnepr.com/',
        order=96,
        show_on_portfolio=False,
    ),
    card(
        slug='polygraph',
        title='Поліграфолог у Львові',
        subtitle='ПЕРЕВІРКА НА ПОЛІГРАФІ',
        title_ru='Полиграфолог во Львове',
        subtitle_ru='ПРОВЕРКА НА ПОЛИГРАФЕ',
        desc='Корпоративний сайт поліграфолога: послуги перевірки, запис, контакти у Львові.',
        desc_ru='Корпоративный сайт полиграфолога: услуги проверки, запись, контакты во Львове.',
        tags=CORP_TAGS,
        site_url='https://polygraph.website/',
        order=97,
        show_on_portfolio=False,
    ),
    card(
        slug='krylova',
        title='Ксенія Крилова',
        subtitle='ВИДАВНИЦТВО',
        title_ru='Ксения Крылова',
        subtitle_ru='ИЗДАТЕЛЬСТВО',
        desc='Корпоративний сайт видавництва Ксенії Крилової: проєкти, співпраця, контакти.',
        desc_ru='Корпоративный сайт издательства Ксении Крыловой: проекты, сотрудничество, контакты.',
        tags=CORP_TAGS,
        site_url='https://krylovakseniia.com/',
        order=21,
    ),
    card(
        slug='school147',
        title='Школа №147',
        subtitle='САЙТ ШКОЛИ',
        title_ru='Школа №147',
        subtitle_ru='САЙТ ШКОЛЫ',
        desc='Корпоративний сайт школи №147 у Києві: новини, розклад, контакти для батьків і учнів.',
        desc_ru='Корпоративный сайт школы №147 в Киеве: новости, расписание, контакты для родителей и учеников.',
        tags=CORP_TAGS,
        site_url='https://school147.kyiv.ua/',
        order=19,
    ),
    card(
        slug='ruh-leo',
        title='RUH LEO',
        subtitle='ФУТБОЛ',
        title_ru='RUH LEO',
        subtitle_ru='ФУТБОЛ',
        desc='Корпоративний сайт футбольного проєкту: про команду, набір, контакти.',
        desc_ru='Корпоративный сайт футбольного проекта: о команде, набор, контакты.',
        tags=CORP_TAGS,
        site_url='https://footballgeneration.com.ua/',
        order=5,
    ),
    card(
        slug='deksor',
        title='ТОВ Дексор',
        subtitle='ЦИФРОВІ ТОВАРИ',
        title_ru='ООО Дексор',
        subtitle_ru='ЦИФРОВЫЕ ТОВАРЫ',
        desc='Корпоративний сайт компанії цифрових товарів і LED-рішень: каталог, заявка, контакти.',
        desc_ru='Корпоративный сайт компании цифровых товаров и LED-решений: каталог, заявка, контакты.',
        tags=CORP_TAGS,
        site_url='https://led-leader.com.ua/',
        order=45,
    ),
    card(
        slug='krashiyvubir',
        title='Кращий Вибір',
        subtitle='БУДІВНИЦТВО',
        title_ru='Лучший Выбор',
        subtitle_ru='СТРОИТЕЛЬСТВО',
        desc='Корпоративний сайт будівельної компанії: послуги, об’єкти, заявка на консультацію.',
        desc_ru='Корпоративный сайт строительной компании: услуги, объекты, заявка на консультацию.',
        tags=CORP_TAGS,
        site_url='https://krashiyvubir.com/',
        order=4,
    ),
    card(
        slug='metrium',
        title='Метріум',
        subtitle='БТІ',
        title_ru='Метриум',
        subtitle_ru='БТИ',
        desc='Корпоративний сайт БТІ-послуг: технічна інвентаризація, заявка, контакти.',
        desc_ru='Корпоративный сайт БТИ-услуг: техническая инвентаризация, заявка, контакты.',
        tags=CORP_TAGS,
        site_url='https://metrium.com.ua/',
        order=17,
    ),
    card(
        slug='pokrivlya',
        title='Покрівля',
        subtitle='ПОКРІВЕЛЬНІ РОБОТИ',
        title_ru='Кровля',
        subtitle_ru='КРОВЕЛЬНЫЕ РАБОТЫ',
        desc='Корпоративний сайт покрівельних робіт: послуги монтажу, заявка, контакти.',
        desc_ru='Корпоративный сайт кровельных работ: услуги монтажа, заявка, контакты.',
        tags=CORP_TAGS,
        site_url='https://pokrivlya.com.ua/',
        order=2,
    ),
    card(
        slug='tenclinic',
        title='TEN CLINIC',
        subtitle='МЕДИЧНА КЛІНІКА',
        title_ru='TEN CLINIC',
        subtitle_ru='МЕДИЦИНСКАЯ КЛИНИКА',
        desc='Корпоративний сайт медичної клініки: послуги, запис на прийом, контакти.',
        desc_ru='Корпоративный сайт медицинской клиники: услуги, запись на приём, контакты.',
        tags=CORP_TAGS,
        site_url='https://tenclinic.com.ua/',
        order=46,
    ),
    card(
        slug='phoenixvet',
        title='Фенікс',
        subtitle='ВЕТЕРИНАРНА КЛІНІКА',
        title_ru='Феникс',
        subtitle_ru='ВЕТЕРИНАРНАЯ КЛИНИКА',
        desc='Корпоративний сайт ветеринарної клініки: послуги, запис, контакти.',
        desc_ru='Корпоративный сайт ветеринарной клиники: услуги, запись, контакты.',
        tags=CORP_TAGS,
        site_url='https://www.phoenixvet.com.ua/',
        order=20,
    ),
    card(
        slug='playvision',
        title='Play Vision',
        subtitle='ФУТБОЛЬНА ОСВІТА',
        title_ru='Play Vision',
        subtitle_ru='ФУТБОЛЬНОЕ ОБРАЗОВАНИЕ',
        desc='PWA-застосунок футбольної освіти: програми, кабінет, запис на навчання.',
        desc_ru='PWA-приложение футбольного образования: программы, кабинет, запись на обучение.',
        tags=('PWA-застосунок', 'особистий кабінет', 'програми навчання', 'заявка'),
        site_url='https://www.playvision.com.ua/',
        order=10,
    ),
    card(
        slug='auto-lot',
        title='CRM Auto-lot',
        subtitle='АВТО',
        title_ru='CRM Auto-lot',
        subtitle_ru='АВТО',
        desc='Веб-застосунок CRM для авто-бізнесу: облік, ліди, кабінет менеджера.',
        desc_ru='Веб-приложение CRM для авто-бизнеса: учёт, лиды, кабинет менеджера.',
        tags=('веб-застосунок', 'CRM', 'кабінет', 'облік лідів'),
        site_url='https://auto-lot.online/',
        order=7,
    ),
]
