"""Нові проєкти портфоліо — магазини та корпоративні з каталогом (частина 2)."""
from apps.core.portfolio_seed_helpers import CATALOG_TAGS, SHOP_TAGS, card

PORTFOLIO_PROJECTS_2 = [
    card(
        slug='beauty-opt',
        title='Beauty Shop',
        subtitle='МАГАЗИН КОСМЕТИКИ',
        title_ru='Beauty Shop',
        subtitle_ru='МАГАЗИН КОСМЕТИКИ',
        desc='Оптовий інтернет-магазин косметики: каталог брендів, швидке оформлення замовлення та доставка по Україні.',
        desc_ru='Оптовый интернет-магазин косметики: каталог брендов, быстрое оформление заказа и доставка по Украине.',
        tags=SHOP_TAGS,
        site_url='https://www.beauty-opt.com.ua/',
        order=29,
    ),
    card(
        slug='gordimarket',
        title='GORDI market',
        subtitle='ТОВАРИ',
        title_ru='GORDI market',
        subtitle_ru='ТОВАРЫ',
        desc='Інтернет-магазин товарів повсякденного попиту: каталог, кошик і зручне оформлення замовлення.',
        desc_ru='Интернет-магазин товаров повседневного спроса: каталог, корзина и удобное оформление заказа.',
        tags=SHOP_TAGS,
        site_url='https://gordimarket.com.ua/',
        order=8,
    ),
    card(
        slug='domoteh',
        title='Domoteh',
        subtitle='ТОВАРИ ДЛЯ ДОМУ',
        title_ru='Domoteh',
        subtitle_ru='ТОВАРЫ ДЛЯ ДОМА',
        desc='Інтернет-магазин товарів для дому та техніки: каталог продукції з онлайн-оплатою та доставкою.',
        desc_ru='Интернет-магазин товаров для дома и техники: каталог продукции с онлайн-оплатой и доставкой.',
        tags=SHOP_TAGS,
        site_url='https://domoteh.shop/',
        order=30,
    ),
    card(
        slug='carpet-haus',
        title='Kylymy',
        subtitle='КИЛИМИ',
        title_ru='Ковры',
        subtitle_ru='КОВРЫ',
        desc='Інтернет-магазин килимів: широкий каталог, фільтри за розміром і стилем, доставка по Україні.',
        desc_ru='Интернет-магазин ковров: широкий каталог, фильтры по размеру и стилю, доставка по Украине.',
        tags=SHOP_TAGS,
        site_url='https://carpet-haus.com.ua/',
        order=31,
    ),
    card(
        slug='svitpc',
        title='Світ ПК',
        subtitle='КОМП’ЮТЕРНА ТЕХНІКА',
        title_ru='Мир ПК',
        subtitle_ru='КОМПЬЮТЕРНАЯ ТЕХНИКА',
        desc='Інтернет-магазин комп’ютерної техніки та комплектуючих: каталог, кошик і онлайн-оплата.',
        desc_ru='Интернет-магазин компьютерной техники и комплектующих: каталог, корзина и онлайн-оплата.',
        tags=SHOP_TAGS,
        site_url='https://svitpc.com.ua/',
        order=11,
    ),
    card(
        slug='geer',
        title='Geer',
        subtitle='ВІЙСЬКОВЕ ТА ТУРИСТИЧНЕ СПОРЯДЖЕННЯ',
        title_ru='Geer',
        subtitle_ru='ВОЕННОЕ И ТУРИСТИЧЕСКОЕ СНАРЯЖЕНИЕ',
        desc='Інтернет-магазин військового та туристичного спорядження: каталог екіпірування з доставкою по Україні.',
        desc_ru='Интернет-магазин военного и туристического снаряжения: каталог экипировки с доставкой по Украине.',
        tags=SHOP_TAGS,
        site_url='https://450geer.com.ua/',
        order=32,
    ),
    card(
        slug='oyra',
        title='Oyra',
        subtitle='ТОВАРИ ДЛЯ ДОМУ',
        title_ru='Oyra',
        subtitle_ru='ТОВАРЫ ДЛЯ ДОМА',
        desc='Інтернет-магазин товарів для дому: каталог декору та побутових речей з онлайн-замовленням.',
        desc_ru='Интернет-магазин товаров для дома: каталог декора и бытовых вещей с онлайн-заказом.',
        tags=SHOP_TAGS,
        site_url='https://oyra.com.ua/',
        order=33,
    ),
    card(
        slug='boltiko',
        title='Boltiko',
        subtitle='КРІПЛЕННЯ ТА МЕТИЗИ',
        title_ru='Boltiko',
        subtitle_ru='КРЕПЁЖ И МЕТИЗЫ',
        desc='Інтернет-магазин шайб, саморізів і кріплення: каталог метизів для будівництва та виробництва.',
        desc_ru='Интернет-магазин шайб, саморезов и крепежа: каталог метизов для строительства и производства.',
        tags=SHOP_TAGS,
        site_url='https://boltiko.com.ua/',
        order=34,
    ),
    card(
        slug='beautycake',
        title='Beauty Cake',
        subtitle='КОНДИТЕРСЬКІ ТОВАРИ',
        title_ru='Beauty Cake',
        subtitle_ru='КОНДИТЕРСКИЕ ТОВАРЫ',
        desc='Інтернет-магазин кондитерських товарів і декору для тортів: каталог інгредієнтів та інструментів.',
        desc_ru='Интернет-магазин кондитерских товаров и декора для тортов: каталог ингредиентов и инструментов.',
        tags=SHOP_TAGS,
        site_url='https://beautycake.com.ua/',
        order=35,
    ),
    card(
        slug='soliron',
        title='Soliron',
        subtitle='СОНЯЧНІ ПАНЕЛІ',
        title_ru='Soliron',
        subtitle_ru='СОЛНЕЧНЫЕ ПАНЕЛИ',
        desc='Інтернет-магазин сонячних панелей та обладнання для зеленої енергетики з доставкою по Україні.',
        desc_ru='Интернет-магазин солнечных панелей и оборудования для зелёной энергетики с доставкой по Украине.',
        tags=SHOP_TAGS,
        site_url='https://soliron.com.ua/',
        order=36,
    ),
    card(
        slug='ogemed',
        title='Ogemed',
        subtitle='КОСМЕТИКА',
        title_ru='Ogemed',
        subtitle_ru='КОСМЕТИКА',
        desc='Інтернет-магазин косметики: каталог догляду за шкірою з оформленням замовлення онлайн.',
        desc_ru='Интернет-магазин косметики: каталог ухода за кожей с оформлением заказа онлайн.',
        tags=SHOP_TAGS,
        site_url='https://oge.in.ua/',
        order=92,
        show_on_portfolio=False,
    ),
    card(
        slug='magnum',
        title='Magnum',
        subtitle='КОРОБКИ ТА УПАКОВКА',
        title_ru='Magnum',
        subtitle_ru='КОРОБКИ И УПАКОВКА',
        desc='Корпоративний каталог виробника коробок і упаковки: продукція, прорахунок замовлення, контакти.',
        desc_ru='Корпоративный каталог производителя коробок и упаковки: продукция, расчёт заказа, контакты.',
        tags=CATALOG_TAGS,
        site_url='https://magnum-tpc.com/uk/',
        order=37,
    ),
    card(
        slug='caryvibe',
        title='CaryVibe',
        subtitle='СУМКИ',
        title_ru='CaryVibe',
        subtitle_ru='СУМКИ',
        desc='Каталог сумок і аксесуарів: вітрина колекцій, заявка та контакти бренду.',
        desc_ru='Каталог сумок и аксессуаров: витрина коллекций, заявка и контакты бренда.',
        tags=CATALOG_TAGS,
        site_url='https://caryvibe.in.ua/',
        order=38,
    ),
    card(
        slug='recharge',
        title='Re-charge',
        subtitle='СИЛОВЕ ОБЛАДНАННЯ',
        title_ru='Re-charge',
        subtitle_ru='СИЛОВОЕ ОБОРУДОВАНИЕ',
        desc='Каталог силового обладнання для залів: тренажери, прорахунок поставки, контакти виробника.',
        desc_ru='Каталог силового оборудования для залов: тренажёры, расчёт поставки, контакты производителя.',
        tags=CATALOG_TAGS,
        site_url='https://recharge4gym.com.ua/uk/',
        order=39,
    ),
    card(
        slug='fortprint',
        title='Фортуна Прінт',
        subtitle='МАРКУВАННЯ',
        title_ru='Фортуна Принт',
        subtitle_ru='МАРКИРОВКА',
        desc='Каталог рішень для маркування та друку: обладнання, заявка на прорахунок, контакти.',
        desc_ru='Каталог решений для маркировки и печати: оборудование, заявка на расчёт, контакты.',
        tags=CATALOG_TAGS,
        site_url='https://www.fortprint.com.ua/',
        order=40,
    ),
    card(
        slug='benzovoz',
        title='Бензовоз',
        subtitle='ЗАПЧАСТИНИ',
        title_ru='Бензовоз',
        subtitle_ru='ЗАПЧАСТИ',
        desc='Каталог запчастин для бензовозів і спецтехніки: позиції, заявка, доставка по Україні.',
        desc_ru='Каталог запчастей для бензовозов и спецтехники: позиции, заявка, доставка по Украине.',
        tags=CATALOG_TAGS,
        site_url='https://www.benzovoz.com.ua/',
        order=14,
    ),
    card(
        slug='notenhaus',
        title='NotenHaus',
        subtitle='НОТИ',
        title_ru='NotenHaus',
        subtitle_ru='НОТЫ',
        desc='Каталог нот і музичних матеріалів: вітрина видань, замовлення, контакти.',
        desc_ru='Каталог нот и музыкальных материалов: витрина изданий, заказ, контакты.',
        tags=CATALOG_TAGS,
        site_url='https://notenhaus.com.ua/',
        order=93,
        show_on_portfolio=False,
    ),
]
