# Generated by Django 4.2.21 on 2026-02-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE payment_paymentlink ADD COLUMN IF NOT EXISTS contract_file varchar(100);",
            reverse_sql="ALTER TABLE payment_paymentlink DROP COLUMN IF EXISTS contract_file;",
            state_operations=[
                migrations.AddField(
                    model_name='paymentlink',
                    name='contract_file',
                    field=models.FileField(blank=True, help_text='Персональний договір для цього посилання', null=True, upload_to='contracts/'),
                ),
            ]
        ),
    ]
