# Generated by Django on 2026-02-23 09:24
from django.db import migrations

from apps.payment.migration_compat import add_column_if_missing


def add_settings_columns(apps, schema_editor):
    add_column_if_missing(
        schema_editor,
        'payment_paymentsettings',
        'title',
        "ALTER TABLE payment_paymentsettings ADD COLUMN IF NOT EXISTS title varchar(255) DEFAULT 'Оплата послуг' NOT NULL;",
    )
    add_column_if_missing(
        schema_editor,
        'payment_paymentsettings',
        'description',
        "ALTER TABLE payment_paymentsettings ADD COLUMN IF NOT EXISTS description text DEFAULT '' NOT NULL;",
    )
    add_column_if_missing(
        schema_editor,
        'payment_paymentsettings',
        'default_contract_file',
        'ALTER TABLE payment_paymentsettings ADD COLUMN IF NOT EXISTS default_contract_file varchar(100) NULL;',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentlink_contract_file'),
    ]

    operations = [
        migrations.RunPython(add_settings_columns, migrations.RunPython.noop),
    ]
