# Generated by Django on 2026-02-23 09:24
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentlink_contract_file'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE payment_paymentsettings ADD COLUMN IF NOT EXISTS title varchar(255) DEFAULT 'Оплата послуг' NOT NULL;
            ALTER TABLE payment_paymentsettings ADD COLUMN IF NOT EXISTS description text DEFAULT '' NOT NULL;
            ALTER TABLE payment_paymentsettings ADD COLUMN IF NOT EXISTS default_contract_file varchar(100) NULL;
            """,
            reverse_sql="""
            ALTER TABLE payment_paymentsettings DROP COLUMN IF EXISTS title;
            ALTER TABLE payment_paymentsettings DROP COLUMN IF EXISTS description;
            ALTER TABLE payment_paymentsettings DROP COLUMN IF EXISTS default_contract_file;
            """,
        ),
    ]