# Generated by Django 4.2.21 on 2026-02-23 09:49

from django.db import migrations, models

from apps.payment.migration_compat import add_column_if_missing


def add_company_info(apps, schema_editor):
    add_column_if_missing(
        schema_editor,
        'payment_paymentlink',
        'company_info',
        "ALTER TABLE payment_paymentlink ADD COLUMN IF NOT EXISTS company_info text NOT NULL DEFAULT '';",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_fix_payment_settings_columns'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_company_info, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='paymentlink',
                    name='company_info',
                    field=models.TextField(blank=True, default=''),
                ),
            ],
        ),
    ]
