# Generated by Django 4.2.21 on 2026-02-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_fix_payment_settings_columns'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE payment_paymentlink ADD COLUMN IF NOT EXISTS company_info text NOT NULL DEFAULT '';",
            reverse_sql="ALTER TABLE payment_paymentlink DROP COLUMN IF EXISTS company_info;",
            state_operations=[
                migrations.AddField(
                    model_name='paymentlink',
                    name='company_info',
                    field=models.TextField(blank=True, default=''),
                ),
            ]
        ),
    ]
