# Generated by Django 4.2.21 on 2026-02-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_paymentlink_company_info'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE payment_paymentlink ADD COLUMN IF NOT EXISTS payment_instructions text NOT NULL DEFAULT '';",
            reverse_sql="ALTER TABLE payment_paymentlink DROP COLUMN IF EXISTS payment_instructions;",
            state_operations=[
                migrations.AddField(
                    model_name='paymentlink',
                    name='payment_instructions',
                    field=models.TextField(blank=True, default=''),
                ),
            ]
        ),
    ]
