# Generated by Django 4.2.21 on 2026-02-23 09:56

from django.db import migrations, models

from apps.payment.migration_compat import add_column_if_missing


def add_payment_instructions(apps, schema_editor):
    add_column_if_missing(
        schema_editor,
        'payment_paymentlink',
        'payment_instructions',
        "ALTER TABLE payment_paymentlink ADD COLUMN IF NOT EXISTS payment_instructions text NOT NULL DEFAULT '';",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_paymentlink_company_info'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_payment_instructions, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='paymentlink',
                    name='payment_instructions',
                    field=models.TextField(blank=True, default=''),
                ),
            ],
        ),
    ]
