# Generated by Django 4.2.21 on 2026-04-05 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_paymentlink_payment_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLinkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='payment_files/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('contract', 'Договір'), ('invoice', 'Рахунок'), ('other', 'Інший документ')], default='contract', max_length=20, verbose_name='Тип')),
                ('name', models.CharField(blank=True, default='', help_text='Якщо не заповнено — показується тип файлу', max_length=255, verbose_name="Назва (необов'язково)")),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('payment_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='payment.paymentlink', verbose_name='Платіжне посилання')),
            ],
            options={
                'verbose_name': 'Файл посилання',
                'verbose_name_plural': 'Файли посилання',
                'ordering': ['file_type', 'uploaded_at'],
            },
        ),
    ]
