# Generated by Django 4.2.21 on 2026-04-05 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_paymentlinkfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва профілю')),
                ('recipient', models.CharField(max_length=255, verbose_name='Отримувач')),
                ('iban', models.CharField(max_length=100, verbose_name='IBAN')),
                ('ipn', models.CharField(max_length=50, verbose_name='ІПН/ЄДРПОУ')),
                ('bank', models.CharField(blank=True, default='', max_length=255, verbose_name='Банк')),
                ('mfo', models.CharField(blank=True, default='', max_length=20, verbose_name='МФО')),
                ('bank_edrpou', models.CharField(blank=True, default='', max_length=20, verbose_name='ЄДРПОУ Банку')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Профіль отримувача (ФОП)',
                'verbose_name_plural': 'Профілі отримувачів (ФОП)',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='use_acquiring',
            field=models.BooleanField(default=True, verbose_name='Увімкнути еквайринг (картка / Apple Pay / Google Pay)'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email клієнта'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='client_name',
            field=models.CharField(max_length=255, verbose_name="Ім'я клієнта"),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='company_info',
            field=models.TextField(blank=True, default='', verbose_name='Реквізити (авто з профілю)'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Опис замовлення'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='payment_instructions',
            field=models.TextField(blank=True, default='', verbose_name='Інструкції'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_links', to='payment.recipientprofile', verbose_name='Отримувач (ФОП)'),
        ),
    ]
