# Generated by Django 4.2.21 on 2026-04-06 09:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_recipientprofile_paymentlink_use_acquiring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlink',
            name='exchange_rate_usd_to_uah',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=12),
        ),
    ]
