# Generated by Django 4.2.21 on 2026-07-20 14:37

import apps.payment.invoice_models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0010_subscription_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(editable=False, unique=True, verbose_name='№ рахунку')),
                ('invoice_date', models.DateField(verbose_name='Дата рахунку')),
                ('valid_until', models.DateField(editable=False, verbose_name='Рахунок доступний до')),
                ('client_name', models.CharField(max_length=255, verbose_name='Замовник (назва / ПІБ)')),
                ('client_tax_id', models.CharField(max_length=20, verbose_name='РНОКПП / ЄДРПОУ')),
                ('client_address', models.CharField(blank=True, default='', max_length=500, verbose_name='Адреса замовника')),
                ('contract_number', models.CharField(max_length=100, verbose_name='Номер договору')),
                ('contract_date', models.DateField(verbose_name='Дата договору')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='Сума')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=apps.payment.invoice_models.invoice_pdf_upload_to, verbose_name='PDF')),
                ('recipient_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('recipient_iban_snapshot', models.CharField(blank=True, default='', max_length=100)),
                ('recipient_ipn_snapshot', models.CharField(blank=True, default='', max_length=50)),
                ('recipient_bank_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('recipient_mfo_snapshot', models.CharField(blank=True, default='', max_length=20)),
                ('recipient_bank_edrpou_snapshot', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='payment.recipientprofile', verbose_name='Виконавець / Отримувач')),
            ],
            options={
                'verbose_name': 'Рахунок',
                'verbose_name_plural': 'Рахунки',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=84)),
            ],
            options={
                'verbose_name': 'Лічильник рахунків',
                'verbose_name_plural': 'Лічильники рахунків',
            },
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Ігнорується при валюті UAH', max_digits=12, verbose_name='Курс до UAH'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='final_amount_uah',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='Сума в UAH'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='status',
            field=models.CharField(choices=[('new', 'Новий'), ('pending', 'Очікує'), ('paid', 'Оплачено'), ('expired', 'Прострочено'), ('deactivated', 'Деактивовано')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='№')),
                ('title', models.TextField(verbose_name='Опис послуги')),
                ('unit', models.CharField(default='послуга', max_length=50, verbose_name='Од.')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12, verbose_name='К-сть')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Ціна')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='Сума')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payment.invoice', verbose_name='Рахунок')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['position', 'id'],
            },
        ),
    ]
