# Generated by Django 4.2.21 on 2026-09-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_invoice_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='data_consent_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Згода на обробку даних для оплати — прийнято'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='data_consent_accepted_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP при підтвердженні згоди на обробку даних'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='withdrawal_waiver_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Момент, коли клієнт підтвердив чекбокс про втрату права відступлення перед оплатою.', null=True, verbose_name='Відмова від 14-денного відступлення — прийнято'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='withdrawal_waiver_accepted_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP при підтвердженні відмови від відступлення'),
        ),
    ]
